### PR TITLE
FEATURE:TMA-1687 - Release/Rollout sync theme object and bump version to 3.7.24

### PR DESCRIPTION
**Pull request by sangtm**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/493/ : SUCCESS in 5s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/497/ : FAILURE in 11m 27s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/494/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/498/ : FAILURE in 11m 20s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/495/ : SUCCESS in 5s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/499/ : FAILURE in 11m 33s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/497/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/501/ : SUCCESS in 23m 35s

**Review by phong-nguyen-duy — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/142/ : SUCCESS in 25m 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/473/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/122/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/41/ : FAILURE in 2m 05s (non-voting)

**Pull request merged**
