### PR TITLE
LR-428: Update the license file for Gooddata-ruby

### PR DESCRIPTION
**Pull request by sangtm**
…

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/604/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/593/ : SUCCESS in 22m 02s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/7/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/605/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/594/ : SUCCESS in 21m 24s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/9/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/607/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/596/ : SUCCESS in 21m 45s

**Comment by sangtm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/10/ : FAILURE in 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/610/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/598/ : SUCCESS in 25m 04s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/11/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/612/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/599/ : SUCCESS in 22m 10s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/12/ : FAILURE in 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/510/ : SUCCESS in 19s
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by sangtm** [comment]
ok to test

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/14/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/511/ : SUCCESS in 18s
- gooddata-ruby-travis-check : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/16/ : FAILURE in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/625/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/609/ : FAILURE in 2m 07s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/17/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/626/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/18/ : FAILURE in 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/627/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/19/ : FAILURE in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/628/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1741

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/33/ : SUCCESS in 3m 27s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/24/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/514/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/72/ : FAILURE in 4m 13s (non-voting)

**Pull request merged**
