### PR TITLE
TMA-522: Rollout: Incorrect CLIENT_ID assigned to client schedule

### PR DESCRIPTION
**Pull request by korczis**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/802/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/758/ : FAILURE in 26m 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/530/ : UNSTABLE in 14m 31s

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/803/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/759/ : FAILURE in 15m 52s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/531/ : UNSTABLE in 4m 59s

**Comment by janchochol** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/806/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/762/ : FAILURE in 14m 27s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/534/ : FAILURE in 24s

**Comment by janchochol** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/807/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/763/ : ABORTED in 41m 31s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/535/ : FAILURE in 23s

**Comment by korczis** [comment]
ok to test

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/813/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/769/ : SUCCESS in 45m 47s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/541/ : UNSTABLE in 14m 13s

**Pull request merged**
