### PR TITLE
Split bundling gems for ruby and jruby images

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/326/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/52/ : FAILURE in 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/364/ : FAILURE in 15s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/327/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/55/ : SUCCESS in 24s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/365/ : FAILURE in 14s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/328/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/56/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/366/ : SUCCESS in 24s

**Comment by hacxman** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/124/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/58/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/368/ : SUCCESS in 2m 21s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/974/ : ABORTED in 3m 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/735/ : FAILURE in 35s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/125/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/59/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/369/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/975/ : SUCCESS in 45m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/736/ : SUCCESS in 22m 55s

**Pull request merged**
