### PR TITLE
Merge hotfix  of 3.0.1 to release

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by Hahihula** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/33/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/934/ : SUCCESS in 40s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1203/ : SUCCESS in 45s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1370/ : ABORTED in 16m 42s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1133/ : FAILURE in 36s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/34/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/935/ : SUCCESS in 41s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1204/ : SUCCESS in 2m 09s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1371/ : SUCCESS in 55m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1137/ : UNSTABLE in 8m 43s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/38/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/940/ : SUCCESS in 46s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1209/ : SUCCESS in 39s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1375/ : FAILURE in 1h 15m 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1141/ : SUCCESS in 33m 53s

**Pull request closed without merging**
