### PR TITLE
 Release gem using travis

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by kubamahnert** [comment]
Looks good, great job @panjan!

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1176/ : SUCCESS in 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/25/ : SUCCESS in 7m 59s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/209/ : SUCCESS in 19s

**Pull request merged**
