### PR TITLE
FEATURE: TMA-1640 Don't trigger PD for CPU limit hit

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/440/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/99/ : FAILURE in 4s
- gooddata-ruby-deploy-pipeline : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/32/ : FAILURE in 2m 05s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/387/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/33/ : SUCCESS in 2m 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/388/ : SUCCESS in 5s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/441/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/100/ : SUCCESS in 5s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-deploy-pipeline/14/ : SUCCESS in 5m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/11/ : SUCCESS in 32s (non-voting)

**Pull request merged**
