### PR TITLE
TMA-1181: passing userprov spec

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by kubamahnert** [comment]
https://travis-ci.org/kubamahnert/gooddata-ruby/builds/454970046

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/810/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1624/ : SUCCESS in 2m 40s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1885/ : SUCCESS in 1m 23s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/64/ : SUCCESS in 7m 00s

**Comment by kubamahnert** [comment]
https://travis-ci.org/kubamahnert/gooddata-ruby/builds/455027642

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/828/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1641/ : SUCCESS in 1m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1902/ : SUCCESS in 1m 13s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/80/ : SUCCESS in 7m 23s

**Comment by jimirocks** [comment]
The lcm integration tests are passing again

**Pull request merged**
