### PR TITLE
Rotate project tokens and rubydev admin password

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/836/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/703/ : SUCCESS in 50s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/964/ : FAILURE in 35s

**Comment by panjan** [comment]
ok to merge

**Comment by kubamahnert** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/837/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/704/ : SUCCESS in 50s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/965/ : FAILURE in 32s

**Comment by kubamahnert** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/838/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/705/ : SUCCESS in 1m 00s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/966/ : FAILURE in 35s

**Pull request merged**
