### PR TITLE
Removing CLI

### PR DESCRIPTION
**Pull request by fluke777**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/334/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/336/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/337/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/339/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
