### PR TITLE
modified docker-compose commpands in rake file to solve the localstac…

### PR DESCRIPTION
**Pull request by Hahihula**
…k problem

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/229/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1072/ : SUCCESS in 1m 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1341/ : FAILURE in 2m 24s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/230/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1436/ : FAILURE in 18m 51s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1188/ : SUCCESS in 33m 02s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-brick-integration-tests-zuul/7/ : FAILURE in 34m 49s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/231/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1074/ : SUCCESS in 1m 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1343/ : SUCCESS in 1m 02s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/232/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1438/ : SUCCESS in 18m 31s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1190/ : SUCCESS in 33m 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-brick-integration-tests-zuul/8/ : FAILURE in 31m 42s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/234/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1439/ : SUCCESS in 28m 21s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1191/ : SUCCESS in 35m 45s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-brick-integration-tests-zuul/9/ : FAILURE in 32m 43s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/236/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1440/ : SUCCESS in 20m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1192/ : SUCCESS in 34m 38s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-brick-integration-tests-zuul/10/ : FAILURE in 35m 32s

**Pull request merged**
