### PR TITLE
Updated the manifest to allow for reference_label specification

### PR DESCRIPTION
**Pull request by fluke777**
New rubocop seems to be release again so there are some violations. Did not fix it now so Mavenlink can investigate and merge the patch to their branch.

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/39/ : FAILURE in 26s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by bobby1190** [comment]
@fluke777 should we be worried about the build failure or can we merge this patch in right now?

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/163/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/101/ : SUCCESS in 40m 09s

**Pull request merged**
