### PR TITLE
BUGFIX: TMA-187 Process name in transfered project must be unique

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/87/ : FAILURE in 15s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by zsvoboda** [comment]
I don't believe that this can work. The condition 

to_project_processes.count(process.name) > 1 

won't work as the to_project_processes contains objects of type process and process.name is String

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/88/ : FAILURE in 14s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by vhtien** [comment]
Thanks for the comment, @zsvoboda

**Comment by vhtien** [comment]
close because of https://github.com/gooddata/gooddata-ruby/pull/727

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/103/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/68/ : FAILURE in 39m 25s

**Pull request merged**
