### PR TITLE
FEATURE: MSF-25417 Revert code to allow LCM image (K8S) run with JRuby latest version 9.4.1.0

### PR DESCRIPTION
**Pull request by hung-nguyen-hoang**
The PR will revert for two commits:

- Revert "Revert "MSF-24148: Upgrade LCM image (K8S) to use JRuby latest version""

- Revert "Revert "MSF-24148: Create environment test for new jruby and ruby version""

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1573/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1418/ : FAILURE in 8m 21s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/45/ : SUCCESS in 15m 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1574/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/40/ : SUCCESS in 18m 00s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/43/ : FAILURE in 13m 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/40/ : FAILURE in 41m 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/45/ : SUCCESS in 22m 03s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/43/ : SUCCESS in 15m 03s

**Comment by ngocmanhha** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1575/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1419/ : SUCCESS in 9m 02s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/46/ : SUCCESS in 16m 24s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1576/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/41/ : SUCCESS in 17m 40s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/44/ : FAILURE in 11m 23s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/41/ : FAILURE in 44m 49s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/46/ : SUCCESS in 23m 10s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/44/ : SUCCESS in 13m 34s

**Comment by tqtu** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1946

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/147/ : SUCCESS in 2m 54s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/39/ : FAILURE in 1m 49s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/689/ : SUCCESS in 10s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/111/ : SUCCESS in 55s

**Pull request merged**
