### PR TITLE
BUGFIX: TMA-406 User filters brick - ignore_missing_values not workin…

### PR DESCRIPTION
**Pull request by vhtien**
…g as expected

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/603/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/547/ : FAILURE in 45m 34s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/318/ : UNSTABLE in 15m 57s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/620/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/570/ : FAILURE in 34s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/339/ : UNSTABLE in 11m 55s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/623/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/573/ : FAILURE in 43m 46s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/342/ : SUCCESS in 20m 52s

**Comment by vhtien** [comment]
ok to test

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/626/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/578/ : FAILURE in 46m 00s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/345/ : UNSTABLE in 12m 01s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/632/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/583/ : FAILURE in 8m 45s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/352/ : UNSTABLE in 4m 49s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/637/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/588/ : FAILURE in 47m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/357/ : SUCCESS in 22m 00s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/643/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/594/ : FAILURE in 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/363/ : UNSTABLE in 6m 18s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/646/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/597/ : FAILURE in 12m 51s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/366/ : UNSTABLE in 5m 41s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/647/ : FAILURE in 46s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/598/ : FAILURE in 12m 52s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/367/ : UNSTABLE in 6m 27s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/653/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/604/ : FAILURE in 45m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/377/ : UNSTABLE in 15m 32s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/659/ : FAILURE in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/610/ : SUCCESS in 46m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/383/ : SUCCESS in 27m 35s

**Pull request merged**
