### PR TITLE
BUGFIX: TMA-445 Users brick does not add user to project when login i…

### PR DESCRIPTION
**Pull request by vhtien**
…s uppercase

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/588/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/529/ : SUCCESS in 42m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/302/ : UNSTABLE in 21m 12s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/599/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/540/ : SUCCESS in 44m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/313/ : SUCCESS in 21m 46s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/619/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/569/ : FAILURE in 34s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/338/ : SUCCESS in 21m 35s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/624/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/574/ : FAILURE in 1h 26m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/343/ : UNSTABLE in 18m 04s

**Comment by vhtien** [comment]
ok to test

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/627/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/576/ : FAILURE in 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/348/ : UNSTABLE in 18m 51s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/630/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/581/ : FAILURE in 1h 06m 13s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/350/ : UNSTABLE in 13m 49s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/638/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/589/ : FAILURE in 46m 26s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/358/ : UNSTABLE in 14m 32s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/644/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/595/ : FAILURE in 12m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/364/ : UNSTABLE in 6m 15s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/645/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/596/ : FAILURE in 12m 51s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/365/ : UNSTABLE in 5m 43s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/654/ : FAILURE in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/605/ : SUCCESS in 47m 12s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/378/ : UNSTABLE in 11m 58s

**Pull request merged**
