### PR TITLE
FEATURE: TMA-215 Attribute Drillpaths Transfer

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/209/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/144/ : FAILURE in 40m 34s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/210/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/145/ : FAILURE in 40m 22s

**Comment by vhtien** [comment]
tests are failed because of https://jira.intgdc.com/browse/BIA-545

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/214/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/149/ : SUCCESS in 42m 58s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/257/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/192/ : SUCCESS in 42m 41s

**Comment by korczis** [comment]
@vhtien Can you rebase this PR, please?

**Comment by korczis** [comment]
LGTM

**Pull request merged**
