### PR TITLE
FEATURE: TMA-1718 - Update license files for gooddata-ruby repo and gooddata gem

### PR DESCRIPTION
**Pull request by sangtm**
…oddata gem

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/602/ : SUCCESS in 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/592/ : SUCCESS in 19m 47s

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1739

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/28/ : SUCCESS in 2m 43s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/507/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/157/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/67/ : FAILURE in 2m 33s (non-voting)

**Pull request merged**
