### PR TITLE
TMA-900: even more VCR

### PR DESCRIPTION
**Pull request by jimirocks**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/214/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1057/ : SUCCESS in 2m 48s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1326/ : SUCCESS in 1m 09s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/216/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1061/ : SUCCESS in 2m 38s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1330/ : SUCCESS in 2m 22s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/217/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1062/ : SUCCESS in 2m 39s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1331/ : SUCCESS in 2m 29s

**Comment by jimirocks** [comment]
build passing: https://travis-ci.org/jimirocks/gooddata-ruby/builds/389107671

**Pull request merged**
