### PR TITLE
Reduce rubocop LineLength by 123 characters

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/423/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/361/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/93/ : FAILURE in 1m 43s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/427/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/365/ : SUCCESS in 42m 09s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/97/ : FAILURE in 10m 19s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/433/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/371/ : FAILURE in 6m 34s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/103/ : FAILURE in 12m 33s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/605/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/557/ : FAILURE in 51s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/320/ : UNSTABLE in 18m 14s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/616/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/566/ : SUCCESS in 44m 47s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/334/ : UNSTABLE in 16m 26s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/622/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/572/ : SUCCESS in 46m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/341/ : UNSTABLE in 18m 21s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/640/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/591/ : FAILURE in 12m 56s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/360/ : UNSTABLE in 15m 26s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/664/ : FAILURE in 30s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/615/ : FAILURE in 1s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/388/ : SUCCESS in 23m 30s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/682/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/636/ : SUCCESS in 45m 07s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/406/ : UNSTABLE in 12m 23s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/690/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/644/ : SUCCESS in 45m 26s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/415/ : SUCCESS in 21m 46s

**Pull request merged**
