### PR TITLE
TMA-584: Move ScheduleExecutionBrick to gooddata-ruby

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/152/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1010/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/156/ : SUCCESS in 20s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/72/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1012/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/158/ : FAILURE in 17s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/73/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1013/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/159/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/898/ : SUCCESS in 45m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/671/ : UNSTABLE in 20m 57s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/76/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1018/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/163/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/901/ : SUCCESS in 45m 18s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/674/ : SUCCESS in 21m 41s

**Pull request merged**
