### PR TITLE
FEATURE: TMA-209 Add support for Email Notification Rules on Process …

### PR DESCRIPTION
**Pull request by vhtien**
…in DIC to Ruby SDK

### CODE REVIEW

**Comment by vhtien** [comment]
@zsvoboda, @korczis please share your feedback. Thanks!

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/109/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/74/ : FAILURE in 40m 56s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/110/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/75/ : FAILURE in 39m 52s

**Comment by korczis** [comment]
Is this more or less done? Is this ready to be merged? Or do you plan some changes?

**Comment by vhtien** [comment]
I need to update CHANGELOG.md and Cookbook

**Comment by vhtien** [comment]
CHANGELOG.md is updated and documentation in cookbook is https://github.com/gooddata/gooddata-ruby-examples/pull/29

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/116/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/78/ : FAILURE in 40m 13s

**Comment by korczis** [comment]
@vhtien Can you rebase this PR, please?

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/123/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/85/ : FAILURE in 36m 45s

**Pull request merged**
