### PR TITLE
CONFIG: MSF-25418 Bump VERSION file to prepare deliver new JRuby for LCM bricks

### PR DESCRIPTION
**Pull request by hung-nguyen-hoang**

### CODE REVIEW

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1577/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1420/ : FAILURE in 8m 16s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/47/ : FAILURE in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1578/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/42/ : SUCCESS in 18m 09s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/45/ : FAILURE in 11m 00s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/43/ : FAILURE in 1h 07m 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/47/ : SUCCESS in 20m 41s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/45/ : SUCCESS in 15m 06s

**Comment by hung-nguyen-hoang** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1581/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1423/ : FAILURE in 8m 16s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/48/ : SUCCESS in 15m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1582/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/43/ : SUCCESS in 17m 03s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/46/ : FAILURE in 10m 58s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/44/ : SUCCESS in 1h 14m 03s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/48/ : SUCCESS in 22m 43s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/46/ : SUCCESS in 13m 15s

**Comment by hung-nguyen-hoang** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1583/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1424/ : SUCCESS in 9m 36s

**Comment by tqtu** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1947

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/192/ : SUCCESS in 7m 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/148/ : SUCCESS in 3m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/40/ : FAILURE in 2m 23s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/690/ : SUCCESS in 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/112/ : SUCCESS in 1m 08s

**Pull request merged**
