### PR TITLE
Don't have to fetch segments again in provisioning clients action

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/277/ : FAILURE in 1s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/212/ : FAILURE in 2s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/307/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/242/ : FAILURE in 1m 54s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/34/ : SUCCESS in 2m 48s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/309/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/244/ : SUCCESS in 42m 43s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/36/ : SUCCESS in 2m 31s (non-voting)

**Comment by korczis** [comment]
LGTM

**Pull request merged**
