### PR TITLE
Separate unit test from integration tests

### PR DESCRIPTION
**Pull request by panjan**
tests that make calls to the API are moved to spec/integration

RELATED: TMA-539

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/13/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/845/ : SUCCESS in 14s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/17/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/849/ : SUCCESS in 16s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/19/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/851/ : SUCCESS in 15s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/29/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/857/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/4/ : SUCCESS in 17s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/30/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/805/ : SUCCESS in 43m 53s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/577/ : SUCCESS in 21m 33s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/3/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/858/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/5/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/807/ : SUCCESS in 44m 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/580/ : UNSTABLE in 14m 06s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/39/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/811/ : SUCCESS in 44m 25s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/584/ : SUCCESS in 20m 13s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/8/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/864/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/11/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/812/ : SUCCESS in 45m 54s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/585/ : UNSTABLE in 8m 30s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/21/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/880/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/27/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/824/ : FAILURE in 31s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/597/ : UNSTABLE in 16m 53s

**Comment by korczis** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/24/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/887/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/34/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/827/ : SUCCESS in 45m 07s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/600/ : SUCCESS in 22m 36s

**Pull request merged**
