### PR TITLE
TMA-301: Make it possible to pass dynamic parameters to schedules

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/108/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/963/ : SUCCESS in 24s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/109/ : SUCCESS in 27s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/137/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/998/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/144/ : SUCCESS in 20s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/139/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1000/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/146/ : SUCCESS in 20s

**Comment by vhtien** [comment]
extended test

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/144/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1005/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/151/ : SUCCESS in 20s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/67/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1006/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/152/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/895/ : SUCCESS in 45m 00s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/668/ : SUCCESS in 21m 06s

**Pull request merged**
