### PR TITLE
Continue with test VCRization

### PR DESCRIPTION
**Pull request by jimirocks**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/97/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/915/ : SUCCESS in 45s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1183/ : SUCCESS in 44s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/109/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/928/ : SUCCESS in 44s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1197/ : SUCCESS in 41s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/173/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1009/ : SUCCESS in 56s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1278/ : FAILURE in 2m 21s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/177/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1013/ : SUCCESS in 2m 07s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1282/ : FAILURE in 2m 25s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/178/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1014/ : SUCCESS in 47s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1283/ : FAILURE in 52s

**Comment by jimirocks** [comment]
build success: https://travis-ci.org/jimirocks/gooddata-ruby/builds/386125493

**Pull request merged**
