### PR TITLE
Revert "FEATURE: MSF-20118 Support PostgreSQL test integration"

### PR DESCRIPTION
**Pull request by tqtu**
Reverts gooddata/gooddata-ruby#1752

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/740/ : SUCCESS in 12s

**Comment by dangdinh** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1775

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/552/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/14/ : SUCCESS in 1m 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/99/ : FAILURE in 2m 58s (non-voting)

**Pull request merged**
