### PR TITLE
FEATURE: MSF-20118 Support PostgreSQL test integration

### PR DESCRIPTION
**Pull request by tqtu**

### CODE REVIEW

**Comment by danh-ung** [comment]
Please move to develop branch

**Comment by tqtu** [comment]
It only used for testing purpose, I will close this ticket when the Travis run successfully.
CC: @danh-ung

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/640/ : SUCCESS in 9s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/617/ : FAILURE in 10m 44s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/641/ : SUCCESS in 11s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/618/ : FAILURE in 12m 17s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/642/ : SUCCESS in 7s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/619/ : FAILURE in 8m 57s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/652/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/620/ : FAILURE in 10m 31s

**Comment by tqtu** [comment]
Close to open on develop branch

**Pull request closed without merging**
