### PR TITLE
BUGFIX: Fix domain.create_users

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/467/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/405/ : FAILURE in 44m 24s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/141/ : SUCCESS in 13m 18s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/468/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/406/ : FAILURE in 43m 51s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/142/ : SUCCESS in 13m 31s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/469/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/407/ : SUCCESS in 47m 06s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/143/ : SUCCESS in 13m 37s

**Pull request merged**
