### PR TITLE
BUGFIX: TMA-1714 Update rotate password and properly template path of lcm test

### PR DESCRIPTION
**Pull request by dangdinh**
Based on new results of travis: https://travis-ci.org/github/gooddata/gooddata-ruby/builds/767535258, we need to update more:
- New IAM Redshift key
- Account/password of snowflake instead of unable account (cornflake)
- New bigquery encrypted key
- Properly template path of lcm test

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/691/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/692/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1757

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/43/ : SUCCESS in 2m 55s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/526/ : SUCCESS in 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/82/ : FAILURE in 2m 38s (non-voting)

**Pull request merged**
