### PR TITLE
Update list of dependencies

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/520/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/261/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/568/ : SUCCESS in 31s

**Comment by kubamahnert** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/176/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/264/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/571/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1070/ : FAILURE in 44m 20s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/829/ : UNSTABLE in 2m 43s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/189/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/280/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/587/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1086/ : SUCCESS in 46m 24s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/845/ : SUCCESS in 23m 44s

**Pull request merged**
