### PR TITLE
FEATURE: TMA-202 Secure parameter handling in LCM bricks

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/81/ : FAILURE in 15s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/85/ : FAILURE in 25s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/86/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/61/ : SUCCESS in 41m 07s

**Comment by korczis** [comment]
LGTM

**Pull request merged**
