### PR TITLE
skip_actions - Skip (do not perform) some actions in chain

### PR DESCRIPTION
**Pull request by korczis**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/722/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/676/ : FAILURE in 45m 19s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/447/ : UNSTABLE in 22m 14s

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/734/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/688/ : FAILURE in 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/459/ : UNSTABLE in 20m 13s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/738/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/692/ : SUCCESS in 45m 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/463/ : UNSTABLE in 20m 20s

**Pull request merged**
