### PR TITLE
TMA-559: Add info about Pronto to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-559

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/282/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1159/ : SUCCESS in 52s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/308/ : SUCCESS in 35s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/95/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1160/ : FAILURE in 13m 36s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/309/ : FAILURE in 3m 44s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by vhtien** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/118/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/41/ : SUCCESS in 1m 22s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/355/ : FAILURE in 0s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/119/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/42/ : SUCCESS in 1m 36s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/356/ : SUCCESS in 3m 34s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/972/ : FAILURE in 45m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/733/ : UNSTABLE in 19m 42s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/120/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/43/ : FAILURE in 2m 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/357/ : FAILURE in 3m 22s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/121/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/44/ : FAILURE in 49s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/358/ : FAILURE in 4m 03s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/122/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/45/ : FAILURE in 54s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/359/ : FAILURE in 3m 26s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/123/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/46/ : FAILURE in 2m 38s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/360/ : FAILURE in 2m 25s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/126/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/61/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/371/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/976/ : SUCCESS in 45m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/737/ : SUCCESS in 24m 50s

**Pull request merged**
