### PR TITLE
TMA-572: Improve API call statistics log: add grouping on CLIENT_ID

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/118/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/972/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/118/ : SUCCESS in 13s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/119/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/866/ : FAILURE in 44m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/640/ : UNSTABLE in 17m 51s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/120/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/868/ : SUCCESS in 44m 47s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/642/ : SUCCESS in 20m 23s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/52/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/975/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/121/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/869/ : SUCCESS in 44m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/643/ : SUCCESS in 21m 33s

**Pull request merged**
