### PR TITLE
TMA-900 VCR continuation

### PR DESCRIPTION
**Pull request by jimirocks**

### CODE REVIEW

**Comment by jimirocks** [comment]
build: https://travis-ci.org/jimirocks/gooddata-ruby/builds/387787817

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/198/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1036/ : SUCCESS in 1m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1305/ : SUCCESS in 2m 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/199/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1037/ : SUCCESS in 2m 56s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1306/ : SUCCESS in 2m 40s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/200/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1038/ : SUCCESS in 1m 23s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1307/ : SUCCESS in 2m 56s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/206/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1048/ : SUCCESS in 2m 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1317/ : SUCCESS in 2m 33s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/207/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1049/ : SUCCESS in 2m 33s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1318/ : SUCCESS in 2m 36s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/208/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1050/ : SUCCESS in 2m 49s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1319/ : SUCCESS in 1m 15s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/211/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1053/ : SUCCESS in 1m 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1322/ : SUCCESS in 1m 11s

**Comment by jimirocks** [comment]
build success: https://travis-ci.org/jimirocks/gooddata-ruby/builds/388701816

**Pull request merged**
