### PR TITLE
RELATED: TMA-244 Add some convinience methods in ADD

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/167/ : FAILURE in 18s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/169/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/106/ : FAILURE in 39m 53s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/182/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/115/ : SUCCESS in 40m 00s

**Pull request merged**
