### PR TITLE
TMA-45: remove commented require from restforce_middleware

### PR DESCRIPTION
**Pull request by hacxman**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/306/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/18/ : SUCCESS in 2m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/329/ : SUCCESS in 3m 49s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/108/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/19/ : SUCCESS in 42s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/330/ : SUCCESS in 40s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/961/ : FAILURE in 45m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/724/ : SUCCESS in 21m 48s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/114/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/34/ : SUCCESS in 1m 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/345/ : SUCCESS in 1m 04s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/965/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/728/ : SUCCESS in 21m 43s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/115/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/38/ : SUCCESS in 43s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/349/ : FAILURE in 0s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/116/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/39/ : SUCCESS in 57s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/353/ : SUCCESS in 1m 58s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/969/ : SUCCESS in 46m 01s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/730/ : SUCCESS in 21m 56s

**Pull request merged**
