### PR TITLE
TMA-639: fix AWS S3 get object

### PR DESCRIPTION
**Pull request by hacxman**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/458/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/190/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/497/ : SUCCESS in 30s

**Comment by hacxman** [comment]
Tests will be later look at TMA-649 in JIRA.

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/159/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/192/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/499/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1047/ : FAILURE in 46m 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/804/ : SUCCESS in 22m 42s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/160/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/193/ : FAILURE in 52s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/500/ : FAILURE in 54s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/161/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/199/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/503/ : SUCCESS in 1m 43s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1048/ : FAILURE in 46m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/805/ : SUCCESS in 23m 57s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/162/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/200/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/504/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1049/ : FAILURE in 46m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/806/ : SUCCESS in 22m 19s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/465/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/203/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/507/ : SUCCESS in 30s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/163/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/204/ : SUCCESS in 38s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/508/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1051/ : FAILURE in 47m 31s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/808/ : SUCCESS in 22m 02s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/164/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/205/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/509/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1052/ : FAILURE in 51m 23s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/809/ : UNSTABLE in 25m 36s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/166/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/216/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/520/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1054/ : SUCCESS in 48m 53s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/811/ : SUCCESS in 23m 57s

**Pull request merged**
