### PR TITLE
TMA-517 Release brick: Each segment can have its own ads_output_stage

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/791/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/747/ : FAILURE in 44m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/519/ : UNSTABLE in 7m 23s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/792/ : SUCCESS in 38s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/748/ : SUCCESS in 44m 32s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/520/ : UNSTABLE in 8m 03s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/796/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/752/ : SUCCESS in 46m 07s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/524/ : UNSTABLE in 7m 57s

**Pull request merged**
