### PR TITLE
TMA-761: add support for manual schedule execution

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/931/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/788/ : SUCCESS in 40s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1056/ : SUCCESS in 3m 21s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/334/ : SUCCESS in 57s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/790/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1058/ : SUCCESS in 2m 27s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1313/ : FAILURE in 6m 13s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1076/ : UNSTABLE in 3m 21s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/335/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/794/ : SUCCESS in 2m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1062/ : SUCCESS in 2m 11s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1316/ : FAILURE in 54m 36s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1079/ : SUCCESS in 34m 10s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/339/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/799/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1067/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1320/ : SUCCESS in 53m 58s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1083/ : SUCCESS in 34m 34s

**Pull request merged**
