### PR TITLE
REFACTOR TMA-478: Please optimize handling of CA attributes in LCM bricks

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/708/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/662/ : SUCCESS in 54m 49s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/433/ : FAILURE in 30s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/729/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/683/ : FAILURE in 44m 18s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/454/ : UNSTABLE in 18m 03s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/742/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/696/ : SUCCESS in 43m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/467/ : FAILURE in 23s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/743/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/697/ : FAILURE in 34m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/468/ : UNSTABLE in 18m 55s

**Pull request merged**
