### PR TITLE
TMA-339: RubySDK middleware connects to wrong cluster when using SST …

### PR DESCRIPTION
**Pull request by korczis**
…in bricks

Fixes tma-339

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/611/ : FAILURE in 46s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/559/ : FAILURE in 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/329/ : UNSTABLE in 11m 59s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/613/ : FAILURE in 45s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/562/ : FAILURE in 45s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/331/ : SUCCESS in 23m 00s

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/614/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/564/ : SUCCESS in 47m 05s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/332/ : UNSTABLE in 13m 25s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/628/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/579/ : SUCCESS in 46m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/347/ : SUCCESS in 22m 33s

**Pull request merged**
