### PR TITLE
Merge develop to master branch

### PR DESCRIPTION
**Pull request by sangtm**
Sync all PRs from develop to master branch (Today: Apr-06-2021)

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/25/ : FAILURE in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/629/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/610/ : SUCCESS in 21m 22s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/26/ : FAILURE in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/515/ : SUCCESS in 23s
- gooddata-ruby-travis-check : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/27/ : FAILURE in 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/516/ : SUCCESS in 20s
- gooddata-ruby-travis-check : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1745

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/34/ : SUCCESS in 3m 01s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/28/ : SUCCESS in 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/517/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/159/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/73/ : FAILURE in 2m 57s (non-voting)

**Pull request merged**
