### PR TITLE
TMA-366: Indicate replacement for technical_user

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-366

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/388/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/123/ : SUCCESS in 1m 48s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/433/ : SUCCESS in 1m 57s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/389/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1031/ : SUCCESS in 46m 23s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/789/ : SUCCESS in 24m 30s

**Comment by kubamahnert** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/218/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/331/ : SUCCESS in 1m 57s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/638/ : SUCCESS in 1m 52s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1116/ : FAILURE in 47m 07s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/871/ : FAILURE in 39s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/219/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/332/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/639/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1117/ : FAILURE in 46m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/872/ : SUCCESS in 23m 43s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/220/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/333/ : FAILURE in 1m 47s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/640/ : FAILURE in 1m 52s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/227/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/344/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/651/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1124/ : SUCCESS in 46m 12s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/880/ : SUCCESS in 24m 02s

**Pull request merged**
