### PR TITLE
TMA-1234: Release

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/248/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/11/ : FAILURE in 6s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/78/ : FAILURE in 49s

**Comment by panjan** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/249/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/12/ : FAILURE in 7s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/79/ : FAILURE in 10m 45s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/250/ : SUCCESS in 32s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/13/ : FAILURE in 8s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/80/ : FAILURE in 2h 58m 22s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1283/ : SUCCESS in 9s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/66/ : FAILURE in 10m 54s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/253/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/14/ : FAILURE in 13s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/81/ : FAILURE in 23s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/254/ : SUCCESS in 1m 15s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/15/ : FAILURE in 19s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/84/ : FAILURE in 10m 42s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/255/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/16/ : FAILURE in 6s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/85/ : FAILURE in 11m 07s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/256/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/17/ : FAILURE in 9s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/86/ : FAILURE in 12m 38s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/257/ : SUCCESS in 1m 03s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/18/ : FAILURE in 14s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/87/ : FAILURE in 12m 47s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1290/ : SUCCESS in 33s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/68/ : FAILURE in 12m 33s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/259/ : SUCCESS in 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/19/ : FAILURE in 21s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/88/ : FAILURE in 13m 11s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1295/ : SUCCESS in 26s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/69/ : FAILURE in 11m 11s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1300/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/70/ : SUCCESS in 13m 17s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/262/ : SUCCESS in 34s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/20/ : FAILURE in 10s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/89/ : SUCCESS in 13m 28s

**Pull request merged**
