### PR TITLE
TMA-632: Fix result for sync_domain_client_workspaces

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/550/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/320/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/627/ : SUCCESS in 38s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/209/ : FAILURE in 12s
- gooddata-ruby-pronto-code-review-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by kubamahnert** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/211/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/322/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/629/ : SUCCESS in 40s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1110/ : FAILURE in 46m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/866/ : SUCCESS in 21m 04s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/216/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/329/ : SUCCESS in 59s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/636/ : SUCCESS in 1m 04s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1114/ : SUCCESS in 44m 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/869/ : SUCCESS in 21m 36s

**Pull request merged**
