### PR TITLE
CONFIG: MSF-26157 change environment testing

### PR DESCRIPTION
**Pull request by tqtu**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/69/ : FAILURE in 2m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1689/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/63/ : FAILURE in 2m 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/66/ : FAILURE in 2m 33s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/65/ : FAILURE in 3m 16s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/68/ : FAILURE in 2m 13s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/67/ : FAILURE in 2m 23s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1688/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1511/ : SUCCESS in 8m 34s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/70/ : FAILURE in 2m 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1691/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/64/ : FAILURE in 2m 44s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/67/ : FAILURE in 2m 11s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/66/ : FAILURE in 6m 07s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/69/ : FAILURE in 2m 10s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/68/ : FAILURE in 2m 19s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1690/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1512/ : SUCCESS in 7m 28s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/71/ : FAILURE in 1m 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1694/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/65/ : FAILURE in 1m 28s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/68/ : FAILURE in 1m 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/67/ : FAILURE in 5m 44s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/70/ : FAILURE in 1m 33s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/69/ : FAILURE in 1m 14s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1693/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1514/ : SUCCESS in 7m 35s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/72/ : SUCCESS in 12m 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1696/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/66/ : SUCCESS in 14m 41s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/69/ : FAILURE in 8m 30s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/68/ : FAILURE in 58m 47s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/71/ : SUCCESS in 18m 49s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/70/ : SUCCESS in 10m 53s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1697/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1516/ : SUCCESS in 7m 35s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/73/ : SUCCESS in 13m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1698/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/67/ : SUCCESS in 15m 40s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/70/ : SUCCESS in 8m 07s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/69/ : SUCCESS in 59m 21s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/72/ : SUCCESS in 18m 02s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/71/ : SUCCESS in 11m 02s

**Review by hung-nguyen-hoang — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1965

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/163/ : SUCCESS in 3m 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/55/ : FAILURE in 3m 00s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/705/ : SUCCESS in 8s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/127/ : SUCCESS in 53s

**Pull request merged**
