### PR TITLE
Merge develop to master

### PR DESCRIPTION
**Pull request by hung-nguyen-hoang**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/715/ : SUCCESS in 9s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/642/ : SUCCESS in 23m 37s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/716/ : SUCCESS in 15s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/643/ : SUCCESS in 21m 41s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/718/ : SUCCESS in 7s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/644/ : SUCCESS in 21m 57s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/535/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/166/ : FAILURE in 23s
- gooddata-ruby-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by hung-nguyen-hoang** [comment]
ok to test

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/536/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/167/ : FAILURE in 5s
- gooddata-ruby-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/721/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/645/ : SUCCESS in 23m 36s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/538/ : SUCCESS in 33s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/168/ : FAILURE in 30s
- gooddata-ruby-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/539/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/169/ : FAILURE in 6s
- gooddata-ruby-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/723/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/647/ : SUCCESS in 22m 56s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/541/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/174/ : FAILURE in 4s
- gooddata-ruby-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Pull request closed without merging**
