### PR TITLE
TMA-811 fixed wrong type in params specification in synchronize users…

### PR DESCRIPTION
**Pull request by Hahihula**
… action

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/909/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/758/ : SUCCESS in 2m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1026/ : SUCCESS in 2m 13s

**Comment by kubamahnert** [comment]
ok to merge

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/323/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/760/ : SUCCESS in 2m 00s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1028/ : SUCCESS in 2m 40s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1301/ : SUCCESS in 52m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1065/ : SUCCESS in 32m 18s

**Pull request merged**
