### PR TITLE
BUGFIX: TMA-1519 Add limit param when get all projects

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1585/ : SUCCESS in 10s

**Comment by phong-nguyen-duy** [comment]
extended test - development

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by phong-nguyen-duy** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/338/ : SUCCESS in 35s

**Pull request merged**
