### PR TITLE
todo: fix move PH_MAP to separate file

### PR DESCRIPTION
**Pull request by hacxman**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/489/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/230/ : FAILURE in 56s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/534/ : SUCCESS in 1m 52s

**Comment by hacxman** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/490/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1056/ : ABORTED in 2h 00m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/813/ : UNSTABLE in 7m 26s

**Comment by hacxman** [comment]
extended test

**Comment by hacxman** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/496/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1057/ : SUCCESS in 48m 07s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/814/ : SUCCESS in 25m 18s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/251/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/449/ : SUCCESS in 1m 46s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/757/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1167/ : FAILURE in 49m 52s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/925/ : SUCCESS in 32m 35s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/252/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/450/ : SUCCESS in 2m 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/758/ : SUCCESS in 1m 56s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1168/ : SUCCESS in 49m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/926/ : SUCCESS in 33m 18s

**Pull request merged**
