### PR TITLE
FEATURE: GDP-539 remove of releaseInfo resource

### PR DESCRIPTION
**Pull request by sitina**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1132/ : SUCCESS in 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/375/ : SUCCESS in 8m 43s

**Comment by panjan** [comment]
Actually, there's one thing we could do better: Throw an exception that says release info is deprecated. I'll push a commit to your PR in a minute.

**Comment by panjan** [comment]
@sitina, does my change look ok to you? ⬆️

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1134/ : SUCCESS in 14s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/377/ : SUCCESS in 8m 09s

**Comment by sitina** [comment]
@panjan LGTM

Thank you!

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/197/ : SUCCESS in 23s

**Pull request merged**
