### PR TITLE
Move user bricks to gooddata-ruby

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-555

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/104/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/958/ : FAILURE in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/104/ : FAILURE in 10s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/105/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/959/ : FAILURE in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/105/ : FAILURE in 13s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/106/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/960/ : FAILURE in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/106/ : FAILURE in 13s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/111/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/965/ : FAILURE in 48s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/111/ : FAILURE in 19s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/112/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/966/ : FAILURE in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/112/ : FAILURE in 13s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/113/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/967/ : FAILURE in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/113/ : FAILURE in 14s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/114/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/968/ : SUCCESS in 42s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/114/ : FAILURE in 21s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/115/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/970/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/116/ : SUCCESS in 20s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/129/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/877/ : SUCCESS in 45m 06s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/651/ : SUCCESS in 22m 03s

**Comment by korczis** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/59/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/989/ : SUCCESS in 41s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/135/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/878/ : SUCCESS in 44m 56s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/652/ : SUCCESS in 21m 22s

**Pull request merged**
