### PR TITLE
INFRA-176: Add sonar-project.properties - cfg file for sonarcloud

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1266/ : SUCCESS in 18s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1137/ : SUCCESS in 12m 03s

**Comment by hung-nguyen-hoang** [comment]
Hi @tomaso I has just fixed failed "**pre-merge / unit-tests (2.7)**". Please rebase the source code to get the fixing code.
Thank you.

**Comment by tomaso** [comment]
> Hi @tomaso I has just fixed failed "**pre-merge / unit-tests (2.7)**". Please rebase the source code to get the fixing code. Thank you.

Thanks a lot @hung-nguyen-hoang - the tests pass now. Can you approve my PR?

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1282/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1152/ : SUCCESS in 11m 10s

**Comment by helobinvn** [comment]
LGTM

**Comment by caohhung** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1893

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/114/ : SUCCESS in 4m 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/6/ : FAILURE in 2m 29s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/656/ : SUCCESS in 19s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/79/ : SUCCESS in 1m 22s

**Pull request merged**
