### PR TITLE
TMA-151: project.compute_report failed on stg2 and stg3

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/35/ : FAILURE in 24s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/36/ : FAILURE in 22s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/37/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/41/ : FAILURE in 1m 23s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Pull request closed without merging**
