### PR TITLE
RELATED: BIA-537 Remove Duplicated Bricks Functionality

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/55/ : FAILURE in 14s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by vhtien** [comment]
should we remove the `scaffold brick` in this file https://github.com/gooddata/gooddata-ruby/blob/develop/CLI.md?

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by korczis** [comment]
We decided to do the opposite. Remove dependency on gooddata-bricks and have bricks implementation in gooddata-ruby. 

This PR is superseded by https://github.com/gooddata/gooddata-ruby/pull/745

**Pull request closed without merging**
