### PR TITLE
Make printing action results more robust

### PR DESCRIPTION
**Pull request by panjan**
so that it doesn't crash with corrupted messages

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/602/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/543/ : ABORTED in 33m 02s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/317/ : UNSTABLE in 12m 52s

**Comment by panjan** [comment]
ok to test

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/606/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/550/ : SUCCESS in 43m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/321/ : UNSTABLE in 11m 49s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/612/ : FAILURE in 43s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/561/ : FAILURE in 46s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/330/ : SUCCESS in 22m 19s

**Pull request merged**
