### PR TITLE
TMA-738: Update highline to v2

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/614/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1147/ : FAILURE in 46m 40s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/905/ : UNSTABLE in 6m 54s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/615/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1148/ : SUCCESS in 48m 54s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/906/ : SUCCESS in 32m 14s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/618/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/413/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/721/ : SUCCESS in 31s

**Pull request closed without merging**
