### PR TITLE
[BIA-220] Segment/Client API

### PR DESCRIPTION
**Pull request by fluke777**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/302/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/304/

**Comment by korczis** [comment]
ok to test

**Comment by korczis** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/306/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/307/

**Comment by fluke777** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/312/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
