### PR TITLE
TMA-419 Support transfer KPI dashboards and AD reports

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/793/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/749/ : FAILURE in 3m 33s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/521/ : UNSTABLE in 14m 23s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/794/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/750/ : FAILURE in 3m 21s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/522/ : UNSTABLE in 13m 41s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/795/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/751/ : SUCCESS in 45m 47s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/523/ : UNSTABLE in 13m 34s

**Pull request merged**
