### PR TITLE
TMA 628: Code coverage calculation

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/498/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/236/ : FAILURE in 56s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/541/ : FAILURE in 54s

**Comment by kubamahnert** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/501/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/238/ : SUCCESS in 1m 44s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/543/ : SUCCESS in 1m 43s

**Comment by kubamahnert** [comment]
extended test

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/502/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1060/ : SUCCESS in 48m 27s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/817/ : FAILURE in 49s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/503/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/239/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/544/ : FAILURE in 53s

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/504/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1061/ : SUCCESS in 46m 29s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/818/ : FAILURE in 33s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/187/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/278/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/585/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1084/ : SUCCESS in 46m 59s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/843/ : UNSTABLE in 3m 00s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/194/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/296/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/603/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1095/ : FAILURE in 44m 02s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/852/ : UNSTABLE in 4m 52s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/202/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/310/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/617/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1104/ : SUCCESS in 47m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/860/ : SUCCESS in 22m 32s

**Pull request merged**
