### PR TITLE
TMA-892: User filters brick dry run

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/11/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/822/ : SUCCESS in 41s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1090/ : SUCCESS in 38s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/6/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/823/ : SUCCESS in 56s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1091/ : SUCCESS in 2m 14s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1333/ : FAILURE in 1m 18s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1096/ : ABORTED in 18m 11s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/13/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1335/ : FAILURE in 54m 54s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1098/ : SUCCESS in 31m 53s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/14/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1336/ : FAILURE in 2m 12s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1099/ : SUCCESS in 37m 24s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/15/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1337/ : FAILURE in 1h 06m 53s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1100/ : SUCCESS in 35m 49s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/16/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/824/ : SUCCESS in 2m 08s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1092/ : SUCCESS in 1m 58s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/17/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1338/ : SUCCESS in 54m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1101/ : SUCCESS in 35m 03s

**Pull request merged**
