### PR TITLE
Fix user permissions in integration tests

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/287/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/7/ : SUCCESS in 2m 08s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/318/ : SUCCESS in 1m 51s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/288/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/940/ : FAILURE in 0s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/710/ : SUCCESS in 25m 31s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/289/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/942/ : SUCCESS in 44m 05s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/711/ : SUCCESS in 21m 32s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/101/ : FAILURE in 9s
- gooddata-ruby-pronto-code-review-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by korczis** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/103/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/10/ : SUCCESS in 1m 53s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/321/ : SUCCESS in 2m 09s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/946/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/715/ : SUCCESS in 21m 22s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/104/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/11/ : SUCCESS in 44s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/322/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/949/ : SUCCESS in 46m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/716/ : SUCCESS in 22m 01s

**Pull request merged**
