### PR TITLE
Fix load tests

### PR DESCRIPTION
**Pull request by panjan**
I lost the schedule_helper.rb file somewhere
and can't find it.

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by kubamahnert** [comment]
When I lose something, it is usually in my jacket or other pants.

Have you checked there?

**Comment by panjan** [comment]
@kubamahnert Good point but in this case the file is lost forever. 🎈

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1128/ : SUCCESS in 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/371/ : SUCCESS in 8m 26s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/194/ : SUCCESS in 22s

**Pull request merged**
