### PR TITLE
Make the CollectClients action more robust

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-489

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/28/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/856/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/3/ : SUCCESS in 2m 44s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/31/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/806/ : SUCCESS in 41m 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/578/ : UNSTABLE in 14m 19s

**Comment by panjan** [comment]
check-extended

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/41/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/815/ : SUCCESS in 44m 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/588/ : UNSTABLE in 6m 36s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/48/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/886/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/33/ : SUCCESS in 2m 54s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/56/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/829/ : SUCCESS in 45m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/602/ : SUCCESS in 21m 50s

**Pull request closed without merging**
