### PR TITLE
TMA-514 User Brick: add language setting

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/804/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/760/ : FAILURE in 3m 43s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/532/ : FAILURE in 33s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/805/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/761/ : FAILURE in 14m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/533/ : FAILURE in 25s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/808/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/764/ : FAILURE in 40m 36s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/536/ : FAILURE in 24s

**Comment by vhtien** [comment]
ok to test - staging

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/810/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/766/ : FAILURE in 1m 38s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/538/ : FAILURE in 27s

**Comment by vhtien** [comment]
ok to test - staging

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/811/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/767/ : FAILURE in 1m 53s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/539/ : UNSTABLE in 12m 56s

**Comment by vhtien** [comment]
ok to test - development

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/812/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/768/ : SUCCESS in 42m 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/540/ : UNSTABLE in 14m 09s

**Pull request merged**
