### PR TITLE
Update image gdc-java-8-jre-centos8 to 202301251553.ee88f24 (from gdc-docker-images)

### PR DESCRIPTION
**Pull request by yenkins-admin**
:exclamation: CAREFULLY REVIEW AFFECTED CLUSTER IDs :exclamation:
:exclamation: Change is delivered immediatelly to the clusters, including production :exclamation:

Change HEAD: https://github.com/gooddata/gdc-docker-images/commit/ee88f24
Pipeline run: [gdc-docker-images/gdc-docker-images-tools-build-pipeline](https://jenkins-ii.intgdc.com/job/gdc-docker-images/job/gdc-docker-images-tools-build-pipeline/566/)

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Supersedes https://github.com/gooddata/gdc-docker-images/pull/1901.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1309/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1179/ : FAILURE in 13m 13s

**Comment by vietnguyenkim-gooddata** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1317/ : SUCCESS in 8s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1187/ : FAILURE in 9m 13s

**Pull request merged**
