### PR TITLE
MSF-17779: Monitor undesired LCM pod status

### PR DESCRIPTION
**Pull request by chiendm**
In case LCM pods can not start due to insufficient resources

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/34/ : SUCCESS in 1m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/521/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/35/ : SUCCESS in 1m 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/522/ : SUCCESS in 5s

**Comment by helobinvn** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1712

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/6/ : SUCCESS in 1m 48s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-deploy-pipeline/15/ : FAILURE in 4m 52s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/479/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/127/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/47/ : SUCCESS in 27s (non-voting)

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- gooddata-ruby-deploy-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/480/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/128/ : FAILURE in 4s
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by helobinvn** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/37/ : SUCCESS in 1m 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/524/ : SUCCESS in 4s

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1712

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/7/ : SUCCESS in 1m 45s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-deploy-pipeline/16/ : FAILURE in 6m 03s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/481/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/129/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/48/ : SUCCESS in 27s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/38/ : SUCCESS in 1m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/525/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- gooddata-ruby-deploy-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/482/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/130/ : FAILURE in 16s
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- gooddata-ruby-deploy-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/483/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/131/ : FAILURE in 4s
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-sonarqube-scan-zuul-el7 : SKIPPED (non-voting)
- gooddata-ruby-deploy-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/484/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/132/ : FAILURE in 4s
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1712

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/8/ : SUCCESS in 2m 20s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-deploy-pipeline/17/ : SUCCESS in 5m 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/485/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/134/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/49/ : SUCCESS in 25s (non-voting)

**Pull request merged**
