### PR TITLE
BUGFIX: TMA-424 Rollout brick synchronize only new computed attribute without drilldrosspath

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/580/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/521/ : FAILURE in 43m 19s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/294/ : UNSTABLE in 29m 36s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/584/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/525/ : FAILURE in 43m 00s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/298/ : UNSTABLE in 23m 05s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/586/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/527/ : SUCCESS in 43m 24s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/300/ : UNSTABLE in 1m 02s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/587/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/528/ : SUCCESS in 44m 30s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/301/ : UNSTABLE in 22m 53s

**Pull request merged**
