### PR TITLE
BUGFIX: TMA-286 Fix spec

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/221/ : FAILURE in 42s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/156/ : FAILURE in 41m 33s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/222/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/157/ : FAILURE in 15s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/223/ : FAILURE in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/158/ : FAILURE in 40m 19s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/224/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/159/ : FAILURE in 46m 12s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/225/ : FAILURE in 15s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/160/ : FAILURE in 43m 45s

**Pull request closed without merging**
