### PR TITLE
Update image gdc-java-8-jre-centos8 to 202304250542.5185484 (from gdc-docker-images)

### PR DESCRIPTION
**Pull request by yenkins-admin**
Change HEAD: https://github.com/gooddata/gdc-docker-images/commit/5185484
Pipeline run: [gdc-docker-images/gdc-docker-images-tools-build-pipeline](https://jenkins-ii.intgdc.com/job/gdc-docker-images/job/gdc-docker-images-tools-build-pipeline/691/)

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Supersedes https://github.com/gooddata/gdc-docker-images/pull/1925.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1521/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1376/ : SUCCESS in 34m 34s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/23/ : FAILURE in 2m 01s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/20/ : FAILURE in 1m 56s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/22/ : FAILURE in 1m 23s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/20/ : FAILURE in 2m 01s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/24/ : FAILURE in 1m 25s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/22/ : FAILURE in 1m 54s

**Comment by yenkins-admin** [comment]
Superseded in run https://jenkins-ii.intgdc.com/job/gdc-docker-images/job/gdc-docker-images-tools-build-pipeline/703/.

**Pull request closed without merging**
