### PR TITLE
More VCR stuff

### PR DESCRIPTION
**Pull request by jimirocks**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/40/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/853/ : SUCCESS in 2m 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1121/ : SUCCESS in 2m 33s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/83/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/899/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1167/ : SUCCESS in 34s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/25/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/912/ : SUCCESS in 2m 06s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1180/ : SUCCESS in 2m 02s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1359/ : SUCCESS in 57m 29s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1122/ : SUCCESS in 33m 53s

**Pull request merged**
