### PR TITLE
BUGFIX: TMA-460 Rollout brick: Changing label's type of attribute is …

### PR DESCRIPTION
**Pull request by vhtien**
…not synchronized to client projects.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/660/ : FAILURE in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/611/ : FAILURE in 1s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/384/ : UNSTABLE in 12m 40s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/661/ : FAILURE in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/612/ : FAILURE in 1s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/385/ : SUCCESS in 21m 51s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/676/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/630/ : SUCCESS in 43m 24s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/400/ : UNSTABLE in 12m 00s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/678/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/632/ : SUCCESS in 45m 13s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/402/ : SUCCESS in 21m 32s

**Pull request merged**
