### PR TITLE
BIA-161 Middlewares automatically transform params into Ruby Hash. This is us…

### PR DESCRIPTION
**Pull request by fluke777**
…eful since Executors platform is passing JRuby Hash structure.

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/168/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
