### PR TITLE
TMA-418: Add debug log in drill path action

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/556/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/496/ : FAILURE in 1h 03m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/237/ : FAILURE in 2m 09s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/570/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/510/ : FAILURE in 43m 09s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/257/ : FAILURE in 1m 32s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/583/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/524/ : SUCCESS in 46m 05s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/297/ : SUCCESS in 20m 30s

**Pull request merged**
