### PR TITLE
TMA-939: VCRize tests listing all the users

### PR DESCRIPTION
**Pull request by jimirocks**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/227/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1070/ : SUCCESS in 1m 23s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1339/ : SUCCESS in 1m 06s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/228/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1071/ : SUCCESS in 1m 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1340/ : SUCCESS in 1m 03s

**Comment by jimirocks** [comment]
build: https://travis-ci.org/jimirocks/gooddata-ruby/builds/391180347

**Comment by panjan** [comment]
ok to merge

**Pull request merged**
