### PR TITLE
Lock version of gooddata-dss-jdbc

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-548

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/95/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/943/ : SUCCESS in 40s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/89/ : FAILURE in 3s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/96/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/944/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/90/ : SUCCESS in 20s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/41/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/946/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/92/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/852/ : FAILURE in 47m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/625/ : FAILURE in 2m 28s

**Comment by panjan** [comment]
extended test

**Comment by korczis** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/98/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/853/ : SUCCESS in 44m 47s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/626/ : FAILURE in 46s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/42/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/947/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/93/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/854/ : SUCCESS in 44m 29s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/627/ : FAILURE in 48s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/44/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/949/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/95/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/856/ : SUCCESS in 44m 52s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/629/ : UNSTABLE in 17m 51s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/45/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/950/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/96/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/857/ : SUCCESS in 45m 36s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/630/ : SUCCESS in 20m 09s

**Pull request merged**
