### PR TITLE
BUGFIX: TMA-1121 use current user call instead of expensive bootstrap

### PR DESCRIPTION
**Pull request by matejuh**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/716/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1541/ : FAILURE in 2m 34s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1802/ : FAILURE in 2m 10s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/717/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1543/ : FAILURE in 10s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul/104/ : FAILURE in 7m 43s

**Comment by matejuh** [comment]
I will create a ticket to SETI- this looks like a bug in CI.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/718/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1542/ : FAILURE in 1m 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1803/ : FAILURE in 3m 24s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/748/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1545/ : FAILURE in 4m 12s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul/106/ : FAILURE in 12m 38s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/778/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1548/ : FAILURE in 11s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul/108/ : FAILURE in 6m 04s

**Pull request closed without merging**
