### PR TITLE
CODE: PAAS-1342 Switch staging2 uri to staging2.intgdc.com

### PR DESCRIPTION
**Pull request by xorel**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/226/

**Comment by fluke777** [comment]
@korczis Tomas, can we merge this? I do not understand exactly why the change in URI but I assume you know about this?

**Comment by korczis** [comment]
@fluke777, Yop I will take care of it ...

**Comment by korczis** [comment]
ok to merge

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
