### PR TITLE
TMA-1714: Merge master to develop

### PR DESCRIPTION
**Pull request by dangdinh**
Due to conflict lib/gooddata/helpers/data_source_helpers.rb file, so we merge master to develop from new branch instead of Github built-in PR

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/1/ : FAILURE in 1m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/582/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/2/ : FAILURE in 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/584/ : SUCCESS in 13s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/3/ : FAILURE in 24s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/585/ : SUCCESS in 11s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/4/ : FAILURE in 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/586/ : SUCCESS in 7s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/5/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/587/ : SUCCESS in 15s

**Comment by yenkins** [comment]
### Sonar scan result
 - 1 BUG
 - 196 CODE_SMELL
 - 2 VULNERABILITY

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1734

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/26/ : FAILURE in 3m 13s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-licenses-validate-LR-ticket-zuul/6/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/505/ : SUCCESS in 1m 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/65/ : FAILURE in 3m 48s (non-voting)

**Pull request merged**
