### PR TITLE
TMA-299 - Use Data Product in LCM bricks

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/61/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/900/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/47/ : SUCCESS in 20s

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/62/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/834/ : FAILURE in 32s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/607/ : UNSTABLE in 1m 44s

**Comment by korczis** [comment]
ok to test

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/65/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/903/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/50/ : SUCCESS in 23s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/66/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/835/ : SUCCESS in 47m 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/608/ : SUCCESS in 21m 31s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/76/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/917/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/63/ : SUCCESS in 15s

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/77/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/840/ : SUCCESS in 44m 41s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/613/ : SUCCESS in 30m 28s

**Pull request closed without merging**
