### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/572/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/512/ : FAILURE in 44m 06s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/259/ : FAILURE in 2m 00s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/573/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/513/ : FAILURE in 49m 59s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/260/ : FAILURE in 2m 23s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/578/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/519/ : SUCCESS in 43m 33s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/292/ : UNSTABLE in 11m 43s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/579/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/520/ : FAILURE in 44m 37s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/293/ : UNSTABLE in 23m 31s

**Comment by vhtien** [comment]
ok to test

**Pull request merged**
