### PR TITLE
TMA-783: Release

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1644/ : SUCCESS in 8s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/243/ : SUCCESS in 22m 21s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/116/ : FAILURE in 5m 08s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/362/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/59/ : SUCCESS in 11s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/117/ : FAILURE in 4m 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/363/ : SUCCESS in 28s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/60/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-lcm-promote-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/364/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/61/ : FAILURE in 29s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-lcm-promote-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/365/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/62/ : FAILURE in 5s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-lcm-promote-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/366/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/63/ : FAILURE in 8s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-lcm-promote-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/367/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/64/ : FAILURE in 5s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-lcm-promote-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/368/ : SUCCESS in 31s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/65/ : FAILURE in 9s

**Comment by vu-pham** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1645/ : SUCCESS in 7s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/244/ : SUCCESS in 25m 31s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/118/ : FAILURE in 1m 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/369/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/67/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/119/ : SUCCESS in 23m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/370/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/68/ : SUCCESS in 7s

**Pull request merged**
