### PR TITLE
Make activesupport a development dependency

### PR DESCRIPTION
**Pull request by panjan**
In order to prevent issues like this:
https://github.com/gooddata/gooddata-ruby/issues/503

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/132/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/994/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/140/ : SUCCESS in 26s

**Comment by korczis** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/62/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/995/ : FAILURE in 3s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/141/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/881/ : SUCCESS in 45m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/655/ : SUCCESS in 23m 31s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/145/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1007/ : SUCCESS in 50s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/153/ : SUCCESS in 25s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/68/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1008/ : SUCCESS in 49s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/154/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/896/ : SUCCESS in 44m 59s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/669/ : SUCCESS in 20m 31s

**Pull request merged**
