### PR TITLE
Automate bumping version

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/329/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1172/ : FAILURE in 1m 21s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1442/ : SUCCESS in 2m 38s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/459/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1290/ : SUCCESS in 1m 27s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1560/ : SUCCESS in 1m 30s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/483/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1314/ : SUCCESS in 58s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1584/ : SUCCESS in 2m 26s

**Pull request merged**
