### PR TITLE
BUGFIX: MSF-22414 Skip non-exist master projects in case of using delete old master workspace

### PR DESCRIPTION
**Pull request by dangdinh**
For some non-exist master workspaces, we need to skip them and continue to delete remaining ones.

Verified on Staging 2 and example log for above should be:
`Unable to remove master workspace: 't0d73662bui00uo84xy2ue8e8ukvj7yz', Error: 404 Not Found: Name t0d73662bui00uo84xy2ue8e8ukvj7yz doesn't exist. request_id: NlSAe3ckaw9tMGqm3aHOSA:177MknvMNfRtAax303dKbw:CxHEcUPNK4idA02gChz0NA:iqHWZgF0e4HjjL7o`

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1815

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/164/ : SUCCESS in 19m 27s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/54/ : SUCCESS in 2m 01s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/596/ : SUCCESS in 16s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/20/ : SUCCESS in 1m 24s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/139/ : FAILURE in 2m 14s (non-voting)

**Pull request merged**
