### PR TITLE
BUGFIX: TMA-407 LCM2 Release brick: do not add PROJECT_ID param to Se…

### PR DESCRIPTION
**Pull request by vhtien**
…gment Masters

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/610/ : FAILURE in 51s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/558/ : FAILURE in 45s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/327/ : SUCCESS in 23m 08s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/618/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/568/ : FAILURE in 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/337/ : UNSTABLE in 17m 30s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/625/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/577/ : FAILURE in 44m 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/344/ : SUCCESS in 22m 01s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/631/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/582/ : FAILURE in 1h 29m 05s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/351/ : UNSTABLE in 5m 54s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/656/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/607/ : FAILURE in 25s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/380/ : SUCCESS in 23m 13s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/658/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/609/ : SUCCESS in 44m 31s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/382/ : UNSTABLE in 12m 38s

**Pull request merged**
