### PR TITLE
Should throw error when sync processes/schedules in segments has problem

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/555/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/495/ : FAILURE in 1h 03m 59s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/236/ : FAILURE in 3m 49s

**Comment by vhtien** [comment]
@panjan I don't know how to create an error for sync processes in segment

**Comment by panjan** [comment]
@vhtien, similarly to the mentioned example, you can stub `segment.synchronize_processes` to return the error. See https://github.com/rspec/rspec-mocks for more details.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/566/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/506/ : FAILURE in 12s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/247/ : FAILURE in 1m 57s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/567/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/507/ : FAILURE in 3m 09s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/248/ : FAILURE in 2m 15s

**Pull request merged**
