### PR TITLE
[BIA-209] The server URI is changed so it is not hardcoded and picked up from c…

### PR DESCRIPTION
**Pull request by fluke777**
…urrent connection

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/273/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/279/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/280/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
