### PR TITLE
TMA-788: req of yard library ~> 0.9.11

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/312/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/677/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/938/ : SUCCESS in 2m 02s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1261/ : ABORTED in 2h 00m 01s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1018/ : ABORTED in 1h 00m 01s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/313/ : FAILURE in 16s
- gooddata-ruby-pronto-code-review-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by Hahihula** [comment]
:banana: ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/314/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/680/ : SUCCESS in 3m 09s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/941/ : SUCCESS in 5m 04s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1265/ : SUCCESS in 57m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1022/ : SUCCESS in 49m 05s

**Pull request merged**
