### PR TITLE
MSF-20653: Bump LCM VERSION 3.7.27

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/803/ : SUCCESS in 17s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/705/ : SUCCESS in 23m 04s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-ruby-lcm-promote-pipeline : SKIPPED
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/566/ : FAILURE in 23s
- gooddata-ruby-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-ruby-fossa-scanning-zuul-el7 : SKIPPED (non-voting)

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1793

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/145/ : SUCCESS in 26m 24s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/567/ : SUCCESS in 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/25/ : SUCCESS in 2m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/110/ : FAILURE in 3m 26s (non-voting)

**Pull request merged**
