### PR TITLE
Resolve hidden reference parameters

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-411

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog
- [x] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/589/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/530/ : FAILURE in 19s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/303/ : UNSTABLE in 1m 16s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/590/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/531/ : FAILURE in 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/304/ : UNSTABLE in 43s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/591/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/532/ : SUCCESS in 46m 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/305/ : UNSTABLE in 19m 51s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/595/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/536/ : FAILURE in 46m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/309/ : UNSTABLE in 13m 57s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/601/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/542/ : SUCCESS in 46m 07s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/315/ : SUCCESS in 22m 50s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/617/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/567/ : FAILURE in 38m 25s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/336/ : SUCCESS in 21m 06s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/621/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/571/ : FAILURE in 44m 45s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/340/ : SUCCESS in 20m 46s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/633/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/584/ : FAILURE in 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/353/ : SUCCESS in 22m 44s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/681/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/635/ : FAILURE in 45m 20s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/405/ : UNSTABLE in 19m 36s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/689/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/643/ : SUCCESS in 44m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/414/ : UNSTABLE in 18m 41s

**Comment by panjan** [comment]
ok to test

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/702/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/656/ : SUCCESS in 52m 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/427/ : SUCCESS in 23m 59s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/705/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/659/ : SUCCESS in 53m 56s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/430/ : FAILURE in 24s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/706/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/660/ : SUCCESS in 54m 27s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/431/ : FAILURE in 26s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/709/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/663/ : SUCCESS in 51m 40s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/434/ : SUCCESS in 25m 37s

**Pull request merged**
