### PR TITLE
[BIA-39] - Multiple dataset uploads

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by korczis** [comment]
https://gist.github.com/korczis/013e083fb6b3eda07fd1

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/204/

**Comment by korczis** [comment]
https://gist.github.com/korczis/013e083fb6b3eda07fd1#file-demo-rb-L86-L100

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/210/

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/211/

**Comment by fluke777** [comment]
Could we create a little example how to use it in case of uploading several files? For documentation purposes?

**Pull request merged**
