### PR TITLE
TMA-809: new visualizationObject in replace_from_mapping

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/737/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/597/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/858/ : SUCCESS in 32s

**Comment by Hahihula** [comment]
Ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/279/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/598/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/859/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1203/ : FAILURE in 47m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/962/ : SUCCESS in 39m 40s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/280/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/599/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/860/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1204/ : FAILURE in 52m 50s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/963/ : SUCCESS in 41m 11s

**Comment by panjan** [comment]
https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1204/ failed for reasons unrelated to this change

**Pull request merged**
