### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Hahihula**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1226/ : SUCCESS in 11s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/54/ : SUCCESS in 15m 07s

**Comment by kubamahnert** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1227/ : SUCCESS in 9s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/55/ : SUCCESS in 11m 41s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/224/ : SUCCESS in 23s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-compliance-check/1/ : FAILURE in 30s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/225/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-compliance-check/2/ : FAILURE in 18s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/226/ : SUCCESS in 21s

**Pull request merged**
