### PR TITLE
FEATURE: MSF-24994 Bring up LCM integration tests to Pipeline

### PR DESCRIPTION
**Pull request by tqtu**

### CODE REVIEW

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1500/ : SUCCESS in 7s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1358/ : SUCCESS in 10m 23s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/1/ : SUCCESS in 15m 50s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/1/ : SUCCESS in 15m 48s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/3/ : FAILURE in 57s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/1/ : SUCCESS in 1h 06m 46s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/3/ : FAILURE in 29s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/3/ : FAILURE in 29s

**Comment by tqtu** [comment]
check-extended

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/4/ : FAILURE in 29s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/3/ : FAILURE in 57s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/5/ : SUCCESS in 10m 46s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/3/ : SUCCESS in 1h 00m 24s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/6/ : FAILURE in 30s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/5/ : FAILURE in 29s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1501/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1359/ : SUCCESS in 10m 29s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/5/ : SUCCESS in 13m 26s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/4/ : SUCCESS in 15m 41s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/6/ : SUCCESS in 12m 07s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/4/ : SUCCESS in 1h 05m 23s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/7/ : SUCCESS in 21m 44s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/6/ : FAILURE in 16m 00s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1502/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1360/ : SUCCESS in 10m 22s

**Comment by vietnguyenkim-gooddata** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/6/ : SUCCESS in 14m 36s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/5/ : SUCCESS in 17m 22s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/7/ : SUCCESS in 14m 02s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/5/ : SUCCESS in 1h 04m 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/8/ : SUCCESS in 21m 37s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/7/ : FAILURE in 16m 17s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1503/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1361/ : SUCCESS in 10m 18s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/7/ : SUCCESS in 13m 30s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/6/ : SUCCESS in 17m 22s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/8/ : SUCCESS in 12m 10s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/6/ : SUCCESS in 1h 06m 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/9/ : FAILURE in 16s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/8/ : FAILURE in 16m 30s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1504/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1362/ : SUCCESS in 10m 39s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/8/ : SUCCESS in 13m 30s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/7/ : SUCCESS in 16m 05s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/9/ : SUCCESS in 12m 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/7/ : SUCCESS in 1h 05m 36s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/10/ : SUCCESS in 21m 52s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/9/ : SUCCESS in 10m 17s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1920

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/127/ : SUCCESS in 2m 49s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/11/ : SUCCESS in 21m 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/8/ : SUCCESS in 15m 45s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/10/ : SUCCESS in 9m 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/669/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/19/ : FAILURE in 4m 53s (non-voting)
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/9/ : SUCCESS in 13m 37s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/92/ : SUCCESS in 1m 01s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/10/ : SUCCESS in 12m 21s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/8/ : FAILURE in 1h 10m 32s

**Comment by vietnguyenkim-gooddata** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1920

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/128/ : SUCCESS in 2m 49s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/12/ : SUCCESS in 21m 22s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/9/ : SUCCESS in 16m 47s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/11/ : SUCCESS in 10m 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/670/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/20/ : FAILURE in 5m 01s (non-voting)
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/10/ : SUCCESS in 13m 30s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/93/ : SUCCESS in 1m 05s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/11/ : SUCCESS in 13m 05s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/9/ : FAILURE in 45m 04s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1920

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/129/ : SUCCESS in 2m 42s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/13/ : SUCCESS in 20m 43s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/10/ : SUCCESS in 18m 30s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/12/ : SUCCESS in 10m 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/671/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/21/ : FAILURE in 4m 58s (non-voting)
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/11/ : SUCCESS in 13m 49s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/94/ : SUCCESS in 1m 02s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/12/ : SUCCESS in 12m 14s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/10/ : FAILURE in 1h 08m 48s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/130/ : SUCCESS in 2m 34s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/14/ : SUCCESS in 22m 21s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/11/ : SUCCESS in 16m 09s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/13/ : SUCCESS in 11m 31s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/672/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/22/ : FAILURE in 4m 54s (non-voting)
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/12/ : SUCCESS in 13m 54s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/95/ : SUCCESS in 1m 23s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/13/ : SUCCESS in 12m 48s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/11/ : FAILURE in 46m 04s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1920

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/131/ : SUCCESS in 3m 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/15/ : FAILURE in 26m 46s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/12/ : FAILURE in 21m 36s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/14/ : FAILURE in 12m 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/673/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/23/ : FAILURE in 5m 49s (non-voting)
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/13/ : SUCCESS in 14m 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/96/ : SUCCESS in 1m 00s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/14/ : FAILURE in 14m 45s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/12/ : FAILURE in 1h 41m 32s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1920

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/132/ : SUCCESS in 2m 48s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/16/ : FAILURE in 24m 53s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/13/ : FAILURE in 18m 41s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/15/ : FAILURE in 7m 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/674/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/24/ : FAILURE in 4m 46s (non-voting)
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/14/ : SUCCESS in 13m 54s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/97/ : SUCCESS in 1m 01s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/15/ : FAILURE in 13m 07s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/13/ : SUCCESS in 1h 04m 47s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1920

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/133/ : SUCCESS in 2m 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/25/ : FAILURE in 6m 37s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/675/ : SUCCESS in 15s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/98/ : SUCCESS in 1m 20s

**Pull request merged**
