### PR TITLE
TMA-542: Release: Should fail when segments contains duplicated ids

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/60/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/899/ : SUCCESS in 45s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/46/ : SUCCESS in 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/63/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/901/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/48/ : SUCCESS in 17s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/64/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/902/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/49/ : SUCCESS in 18s

**Comment by panjan** [comment]
@vhtien, what do you think about these changes? https://github.com/vhtien/gooddata-ruby/pull/1

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/67/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/904/ : SUCCESS in 40s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/51/ : SUCCESS in 21s

**Comment by vhtien** [comment]
Thanks @panjan

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/28/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/905/ : SUCCESS in 23s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/52/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/836/ : SUCCESS in 44m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/609/ : SUCCESS in 23m 35s

**Pull request merged**
