### PR TITLE
TMA-601: Remove CLIENT_ID setting from LCM bricks

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/333/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/66/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/376/ : FAILURE in 26s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/334/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/67/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/377/ : SUCCESS in 27s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/335/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/981/ : SUCCESS in 47m 43s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/740/ : SUCCESS in 22m 25s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/337/ : SUCCESS in 52s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/68/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/378/ : SUCCESS in 26s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/338/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/983/ : SUCCESS in 46m 43s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/742/ : UNSTABLE in 1m 31s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/346/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/986/ : SUCCESS in 50m 30s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/745/ : UNSTABLE in 26m 40s

**Comment by vhtien** [comment]
Fix integration tests: https://ms-gerrit.intgdc.com/#/c/1555/

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/132/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/80/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/390/ : SUCCESS in 36s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/992/ : SUCCESS in 46m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/751/ : ABORTED in 1h 00m 00s

**Comment by panjan** [comment]
Do not merge until [MSF-12914](https://jira.intgdc.com/browse/MSF-12914) is resolved.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/186/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/276/ : SUCCESS in 1m 20s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/583/ : SUCCESS in 1m 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1082/ : SUCCESS in 48m 42s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/841/ : UNSTABLE in 25m 17s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/190/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/283/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/590/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1087/ : SUCCESS in 48m 02s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/846/ : UNSTABLE in 26m 23s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/217/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/330/ : SUCCESS in 2m 49s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/637/ : SUCCESS in 2m 50s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1115/ : SUCCESS in 43m 48s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/870/ : UNSTABLE in 21m 41s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/228/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/348/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/655/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1125/ : SUCCESS in 46m 33s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/881/ : UNSTABLE in 22m 24s

**Comment by jimirocks** [comment]
extended test

**Comment by jimirocks** [comment]
MSF-12914 is resolved for long time

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/823/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1268/ : FAILURE in 1h 07m 45s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1028/ : UNSTABLE in 59m 22s

**Comment by kubamahnert** [comment]
Closed in favour of https://github.com/gooddata/gooddata-ruby/pull/1140

**Pull request closed without merging**
