### PR TITLE
Make Connection#format_error more robust

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/369/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/304/ : FAILURE in 2m 30s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/35/ : FAILURE in 8m 05s

**Comment by panjan** [comment]
ok to test

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/392/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/332/ : SUCCESS in 42m 21s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/60/ : FAILURE in 7m 55s

**Pull request merged**
