### PR TITLE
TMA-956 - Update process.rb to fix regression from TMA-832

### PR DESCRIPTION
**Pull request by vladimir-pachnik**
- users were not be able to re-deploy process due to :process_id being nil

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/235/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1076/ : SUCCESS in 3m 55s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1345/ : SUCCESS in 3m 48s

**Comment by kubamahnert** [comment]
Looks like a good start! Is it possible to cover the change in a unit test?

**Comment by vladimir-pachnik** [comment]
I can try. Do you want me to the the private `save` method or the public `deploy_simple_process`?

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/258/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1104/ : FAILURE in 2m 44s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1373/ : FAILURE in 2m 46s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/259/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1105/ : FAILURE in 2m 50s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1374/ : FAILURE in 1m 31s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/260/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1106/ : FAILURE in 1m 22s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1375/ : FAILURE in 1m 15s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/261/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1107/ : FAILURE in 2m 53s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1376/ : FAILURE in 2m 27s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/296/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1144/ : FAILURE in 1m 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1414/ : SUCCESS in 1m 07s

**Comment by Hahihula** [comment]
Because of still unresolved problems I took this over and merged in pull request https://github.com/gooddata/gooddata-ruby/pull/1248

**Pull request closed without merging**
