### PR TITLE
Fix failing rubocop check

### PR DESCRIPTION
**Pull request by panjan**
## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog
- [x] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/667/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/621/ : SUCCESS in 44m 42s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/391/ : UNSTABLE in 22m 26s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/668/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/622/ : FAILURE in 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/392/ : SUCCESS in 21m 50s

**Comment by panjan** [comment]
ok to test - testing

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/669/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/623/ : FAILURE in 30m 51s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/393/ : SUCCESS in 23m 00s

**Comment by panjan** [comment]
ok to test - testing

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/670/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/624/ : FAILURE in 43m 14s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/394/ : SUCCESS in 22m 00s

**Comment by panjan** [comment]
ok to test - staging

**Comment by panjan** [comment]
ok to test - development

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/671/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/625/ : FAILURE in 42m 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/395/ : UNSTABLE in 12m 51s

**Comment by panjan** [comment]
ok to test - development

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/672/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/626/ : FAILURE in 41m 47s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/396/ : SUCCESS in 21m 28s

**Comment by panjan** [comment]
ok to test - testing

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/673/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/627/ : FAILURE in 45m 55s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/397/ : SUCCESS in 23m 17s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/674/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/628/ : FAILURE in 23s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/398/ : ABORTED in 2m 26s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/675/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/629/ : SUCCESS in 45m 32s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/399/ : SUCCESS in 22m 44s

**Pull request merged**
