### PR TITLE
fixed cyclic decrypting of encrypted password

### PR DESCRIPTION
**Pull request by Hahihula**

### CODE REVIEW

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/221/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1432/ : FAILURE in 19m 24s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul/16/ : SUCCESS in 37m 39s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-brick-integration-tests-zuul/1/ : FAILURE in 15s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/223/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1433/ : FAILURE in 19m 53s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1185/ : SUCCESS in 33m 09s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-brick-integration-tests-zuul/3/ : FAILURE in 18s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/224/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1434/ : FAILURE in 19m 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1186/ : SUCCESS in 37m 43s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-brick-integration-tests-zuul/5/ : FAILURE in 33m 34s

**Comment by Hahihula** [comment]
extended test

**Pull request merged**
