### PR TITLE
TMA-593: LCM2 bricks: Log start of each action

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/246/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1119/ : FAILURE in 4s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/268/ : SUCCESS in 22s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/247/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1120/ : FAILURE in 4s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/269/ : SUCCESS in 21s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/250/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1123/ : FAILURE in 7s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/272/ : SUCCESS in 22s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/266/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1136/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/285/ : SUCCESS in 22s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/87/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1142/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/291/ : SUCCESS in 24s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/927/ : SUCCESS in 45m 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/697/ : UNSTABLE in 1m 22s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/97/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/4/ : SUCCESS in 1m 02s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/315/ : SUCCESS in 43s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/937/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/707/ : SUCCESS in 22m 45s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/105/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/12/ : SUCCESS in 2m 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/323/ : SUCCESS in 1m 56s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/950/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/717/ : SUCCESS in 21m 21s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/106/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/13/ : SUCCESS in 1m 25s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/324/ : SUCCESS in 36s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/951/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/718/ : SUCCESS in 22m 59s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/107/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/14/ : SUCCESS in 53s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/325/ : SUCCESS in 1m 57s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/957/ : SUCCESS in 46m 51s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/720/ : SUCCESS in 21m 15s

**Pull request merged**
