### PR TITLE
Relax ActiveSupport dependency

### PR DESCRIPTION
**Pull request by henrich-m**
The ActiveSupport version specification is too restrictive, it makes impossible to use the gem with Rails 5.
This PR relax the dependency to make the gem Rails 5 compatible.

### CODE REVIEW

**Comment by kubamahnert** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1052/ : SUCCESS in 8s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/302/ : SUCCESS in 9m 01s

**Comment by henrich-m** [comment]
Thanks @panjan, this will enable us to update the rails version of our app ;D

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/169/ : SUCCESS in 44s

**Comment by andrehjr** [comment]
Hey guys, can you release a new version with this change? Thanks!

**Comment by panjan** [comment]
Hi @andrehjr! Gem released. 😉

**Comment by andrehjr** [comment]
Thanks so much Jan! :)

**Comment by panjan** [comment]
@andrehjr, I've just found out the released gem fails to load. A fix is being merged and will be released shortly.

**Pull request merged**
