### PR TITLE
TMA-809: Fix new visualization object

### PR DESCRIPTION
**Pull request by Hahihula**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/735/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/585/ : SUCCESS in 38s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/846/ : SUCCESS in 42s

**Comment by kubamahnert** [comment]
Looks good!

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/269/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/586/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/847/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1193/ : FAILURE in 55m 06s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/951/ : UNSTABLE in 39m 31s

**Comment by kubamahnert** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/281/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/600/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/861/ : SUCCESS in 44s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1205/ : FAILURE in 51m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/964/ : UNSTABLE in 41m 58s

**Pull request closed without merging**
