### PR TITLE
Remove deleting all ADS instances from tests

### PR DESCRIPTION
**Pull request by panjan**
will be handled in TMA-667

### CODE REVIEW

**Comment by kubamahnert** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/174/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/262/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/569/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1068/ : FAILURE in 43m 18s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/827/ : UNSTABLE in 2m 47s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/175/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/263/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/570/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1069/ : FAILURE in 40m 55s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/828/ : UNSTABLE in 2m 40s

**Comment by kubamahnert** [comment]
extended test - staging

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/522/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1073/ : FAILURE in 43m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/832/ : FAILURE in 29s

**Pull request merged**
