### PR TITLE
BUGFIX: TMA-1694 Bump bricks version to 3.7.25

### PR DESCRIPTION
**Pull request by hung-nguyen-hoang**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/592/ : SUCCESS in 7s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/582/ : SUCCESS in 24m 37s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/593/ : SUCCESS in 10s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/583/ : SUCCESS in 21m 48s

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1735

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/29/ : SUCCESS in 2m 49s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/143/ : SUCCESS in 26m 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/508/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/158/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/68/ : FAILURE in 2m 48s (non-voting)

**Pull request merged**
