### PR TITLE
BUGFIX: TMA-429 Release Brick: Can not import Computed Attribute that…

### PR DESCRIPTION
**Pull request by vhtien**
… add on Dashboard

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/592/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/533/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/306/ : UNSTABLE in 29m 37s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/593/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/534/ : FAILURE in 46m 29s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/307/ : UNSTABLE in 23m 54s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/600/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/541/ : FAILURE in 44m 36s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/314/ : SUCCESS in 22m 00s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/609/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/560/ : FAILURE in 50s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/326/ : FAILURE in 4m 13s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/615/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/565/ : SUCCESS in 44m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/333/ : SUCCESS in 21m 47s

**Pull request merged**
