### PR TITLE
[BIA-238] Fixed the call of methods in execute so the nested parameters are enc…

### PR DESCRIPTION
**Pull request by fluke777**
…oded correctly

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/293/

**Comment by korczis** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/295/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/298/

**Pull request merged**
