### PR TITLE
get_dashboards, transfer_meta, transfer_tagged_stuff

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/79/ : FAILURE in 12s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/80/ : FAILURE in 12s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/162/ : FAILURE in 6s
- gooddata-ruby-tests-zuul : SKIPPED

**Pull request closed without merging**
