### PR TITLE
Feature/bia 37 - CLI for vertica projects

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by korczis** [comment]
Ready to test.

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/49/

**Pull request merged**
