### PR TITLE
FEATURE: TMA-1034 Add Docker label containing LCM bricks version

### PR DESCRIPTION
**Pull request by sadam21**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/750/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1572/ : FAILURE in 2m 40s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1833/ : FAILURE in 2m 11s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/13/ : FAILURE in 14s

**Comment by sadam21** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/753/ : SUCCESS in 1m 00s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1575/ : FAILURE in 1m 55s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1836/ : FAILURE in 1m 31s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/16/ : FAILURE in 22s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/762/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1584/ : FAILURE in 1m 49s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1845/ : SUCCESS in 2m 34s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/24/ : SUCCESS in 7m 23s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/764/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1586/ : SUCCESS in 1m 08s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1847/ : FAILURE in 3m 05s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/26/ : SUCCESS in 6m 46s

**Comment by sadam21** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/765/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1587/ : SUCCESS in 2m 42s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1848/ : FAILURE in 1m 34s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/27/ : FAILURE in 32s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/769/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1590/ : SUCCESS in 1m 06s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1851/ : FAILURE in 1m 46s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/30/ : FAILURE in 26s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/770/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1591/ : SUCCESS in 3m 09s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1852/ : SUCCESS in 4m 17s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/31/ : FAILURE in 34s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/771/ : SUCCESS in 1m 29s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1592/ : SUCCESS in 2m 37s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1853/ : SUCCESS in 3m 31s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/32/ : SUCCESS in 8m 48s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/772/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1593/ : SUCCESS in 1m 06s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1854/ : SUCCESS in 1m 15s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/33/ : FAILURE in 1m 05s

**Comment by sadam21** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/773/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1594/ : SUCCESS in 1m 07s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1855/ : SUCCESS in 1m 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/34/ : SUCCESS in 6m 31s

**Pull request merged**
