### PR TITLE
rotate integration test projects

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by Hahihula** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/892/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/751/ : SUCCESS in 2m 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1019/ : SUCCESS in 1m 56s

**Comment by kubamahnert** [comment]
extended test

**Comment by kubamahnert** [comment]
extended test - staging

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/893/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1281/ : ABORTED in 2h 00m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1045/ : FAILURE in 1m 20s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/894/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1282/ : ABORTED in 54m 33s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1046/ : UNSTABLE in 41m 45s

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/895/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1283/ : FAILURE in 55m 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1047/ : UNSTABLE in 41m 18s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/896/ : SUCCESS in 48s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/752/ : SUCCESS in 44s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1020/ : SUCCESS in 46s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/898/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1284/ : FAILURE in 1h 38m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1048/ : UNSTABLE in 40m 45s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/901/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1287/ : SUCCESS in 55m 42s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1051/ : UNSTABLE in 45m 13s

**Pull request merged**
