### PR TITLE
[BIA-147]: The date_fact was ignored when generating manifest. Fixed plus added test.

### PR DESCRIPTION
**Pull request by fluke777**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/119/

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/120/

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/121/

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/170/

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/177/

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/184/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
