### PR TITLE
TMA-622: Result of CollectSegments should contain MASTER_PID instead …

### PR DESCRIPTION
**Pull request by vhtien**
…of DEVELOPMENT_PID column

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/371/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/106/ : SUCCESS in 1m 52s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/416/ : SUCCESS in 1m 54s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/153/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/115/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/425/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1023/ : SUCCESS in 46m 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/781/ : UNSTABLE in 15m 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/383/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/118/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/428/ : SUCCESS in 34s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/154/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/119/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/429/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1027/ : SUCCESS in 42m 50s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/785/ : UNSTABLE in 4m 59s

**Pull request closed without merging**
