### PR TITLE
TMA-551: Release: Improve log for SynchronizeProcesses and SynchronizeSchedules actions

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/57/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/894/ : SUCCESS in 37s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/41/ : SUCCESS in 15s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/58/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/830/ : SUCCESS in 46m 36s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/603/ : SUCCESS in 22m 12s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/25/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/896/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/43/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/831/ : SUCCESS in 47m 19s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/604/ : SUCCESS in 23m 16s

**Pull request merged**
