### PR TITLE
[BIA-176] + [BIA-177] - Notification support

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/285/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/286/

**Comment by korczis** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/315/

**Comment by korczis** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/316/

**Comment by korczis** [comment]
ok to test

**Comment by korczis** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/390/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/391/

**Pull request closed without merging**
