### PR TITLE
Add missing changelogs

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/125/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/983/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/129/ : SUCCESS in 20s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/126/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/984/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/130/ : SUCCESS in 20s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/61/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/992/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/138/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/880/ : SUCCESS in 45m 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/654/ : SUCCESS in 22m 59s

**Pull request merged**
