### PR TITLE
Fix console command

### PR DESCRIPTION
**Pull request by petr-tichy**
- respect server setting
- make project parameter optional

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/389/

**Comment by korczis** [comment]
ok to test

**Comment by korczis** [comment]
@petr-tichy can you rebase this, please?

**Comment by petr-tichy** [comment]
Actually not. Apparently most cli commands were deleted in 4d5bd84ad3ea8d450d15d99853d20af61b7a8422 titled "Added stuff" by @fluke777 - intention?

**Pull request closed without merging**
