### PR TITLE
BIA-75 link to cookbook in readme

### PR DESCRIPTION
**Pull request by cvengros**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/9/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
