### PR TITLE
Remove monkey patchs from Hash

### PR DESCRIPTION
**Pull request by henrich-m**
Just remove monkey-patchs that already exists in `ActiveSupport` gem.

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/351/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 7s
- gooddata-ruby-pronto-code-review-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED

**Comment by henrich-m** [comment]
Hi @panjan, when I was upgrading the gem in our [app](https://www.rdstation.com.br) we got some errors on our CI, we investigated and found some monkeypatchs that gooddata gem made, the majority of them are already in `ActiveRecord` and the `deep_merge`  was being overwritten, monkeypatchs are really powerfull and dangerous and should be handled with extreme care, I renamed the `Hash.deep_merge` to `Hash.custom_deep_merge` so it don't  overwrite the `ActiveRecord` implementation, as we use it and other people could be using too and facing problems. 
This makes any sense to you ?

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/100/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1206/ : SUCCESS in 1m 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1476/ : SUCCESS in 1m 02s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1464/ : FAILURE in 11m 52s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul/36/ : SUCCESS in 35m 10s

**Comment by henrich-m** [comment]
@panjan I'm closing this PR in favor of #1252 as it resolves all the monkey patches in one shot ;)
I think some integration tests maybe break but we can work those in the upcoming weeks.

**Pull request closed without merging**
