### PR TITLE
BIA-163: Fixing error messages in export/import. Import export can be called s…

### PR DESCRIPTION
**Pull request by fluke777**
…eparately. Tranfer takes multiple projects and migrates them with just one export.

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/182/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
