### PR TITLE
Fix transferring secure params

### PR DESCRIPTION
**Pull request by panjan**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

RELATED: TMA-508

### CODE REVIEW

**Comment by panjan** [comment]
ok to test - staging

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/765/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/721/ : SUCCESS in 45m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/490/ : UNSTABLE in 11m 41s

**Comment by panjan** [comment]
ok to test - staging

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/766/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/722/ : FAILURE in 1m 26s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/492/ : UNSTABLE in 11m 55s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/769/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/725/ : SUCCESS in 47m 20s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/495/ : FAILURE in 28s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/771/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/727/ : SUCCESS in 45m 30s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/497/ : UNSTABLE in 17m 12s

**Pull request merged**
