### PR TITLE
RELATED: TMA-317 Set the client specific title to client settings

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/322/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/257/ : FAILURE in 44m 59s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/49/ : FAILURE in 2m 37s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/325/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/261/ : SUCCESS in 42m 34s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/53/ : FAILURE in 3m 01s (non-voting)

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/326/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/262/ : SUCCESS in 42m 57s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/54/ : FAILURE in 2m 57s (non-voting)

**Comment by korczis** [comment]
LGTM

**Pull request merged**
