### PR TITLE
revert of the not failing o nmandatory param outside the tests

### PR DESCRIPTION
**Pull request by Hahihula**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/251/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1097/ : SUCCESS in 3m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1366/ : FAILURE in 2m 49s

**Comment by panjan** [comment]
https://jira.intgdc.com/browse/TMA-964

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/252/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1098/ : SUCCESS in 2m 51s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1367/ : FAILURE in 2m 30s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/254/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1100/ : SUCCESS in 2m 47s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1369/ : SUCCESS in 2m 30s

**Pull request closed without merging**
