### PR TITLE
TMA-775: make attribute polling smarter again

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/718/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/552/ : SUCCESS in 1m 01s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/829/ : SUCCESS in 2m 08s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/719/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/553/ : SUCCESS in 3m 03s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/830/ : SUCCESS in 37s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/720/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/554/ : SUCCESS in 1m 53s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/831/ : SUCCESS in 2m 25s

**Comment by panjan** [comment]
ok to merge

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/721/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1191/ : FAILURE in 1h 08m 53s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/949/ : UNSTABLE in 55m 53s

**Comment by kubamahnert** [comment]
the failures are expected because the tests are for 2.2 testing functionality that was fixed in 2.2 but is still broken in 2.1

**Pull request merged**
