### PR TITLE
BUGFIX: TMA-441 The data upload in ADD schedule shows wrong option in…

### PR DESCRIPTION
**Pull request by vhtien**
… project version

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/629/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/580/ : FAILURE in 56m 49s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/349/ : UNSTABLE in 18m 52s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/655/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/606/ : FAILURE in 27m 41s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/379/ : UNSTABLE in 12m 03s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/657/ : FAILURE in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/608/ : SUCCESS in 43m 38s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/381/ : SUCCESS in 22m 17s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/679/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/633/ : SUCCESS in 44m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/403/ : UNSTABLE in 12m 05s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/685/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/639/ : FAILURE in 29s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/409/ : UNSTABLE in 1m 41s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/686/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/640/ : FAILURE in 44m 29s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/410/ : SUCCESS in 20m 34s

**Pull request merged**
