### PR TITLE
RELATED: TMA-243 Support custom color palette in project

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/202/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/137/ : FAILURE in 41m 11s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/203/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/138/ : SUCCESS in 41m 36s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/205/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/140/ : SUCCESS in 40m 35s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/229/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/164/ : SUCCESS in 41m 47s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/255/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/190/ : SUCCESS in 41m 21s

**Pull request merged**
