### PR TITLE
Update image gdc-java-8-jre-centos8 to 202306121212.f55ddaf (from gdc-docker-images)

### PR DESCRIPTION
**Pull request by yenkins-admin**
Change HEAD: https://github.com/gooddata/gdc-docker-images/commit/f55ddaf
Pipeline run: [gdc-docker-images/gdc-docker-images-tools-build-pipeline](https://jenkins-ii.intgdc.com/job/gdc-docker-images/job/gdc-docker-images-tools-build-pipeline/744/)

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Supersedes https://github.com/gooddata/gdc-docker-images/pull/1933.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1536/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1390/ : SUCCESS in 26m 41s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/35/ : SUCCESS in 12m 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1537/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/30/ : SUCCESS in 17m 53s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/33/ : FAILURE in 9m 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/30/ : FAILURE in 1h 02m 58s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/34/ : SUCCESS in 22m 28s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/33/ : SUCCESS in 15m 27s

**Comment by yenkins-admin** [comment]
Superseded in run https://jenkins-ii.intgdc.com/job/gdc-docker-images/job/gdc-docker-images-tools-build-pipeline/757/.

**Pull request closed without merging**
