### PR TITLE
Fix middleware

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by vhtien** [comment]
may I ask why `bench_middleware.rb` and `fs_upload_middleware.rb` are not required?

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/388/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/323/ : SUCCESS in 42m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/54/ : FAILURE in 2m 45s

**Comment by korczis** [comment]
@vhtien Ouch, my mistake. Thanks for spotting this.

**Comment by panjan** [comment]
@korczis, is this still valid?

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/718/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/672/ : FAILURE in 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/443/ : UNSTABLE in 3m 01s

**Pull request closed without merging**
