### PR TITLE
Fix vcr rspec example

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/201/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1039/ : SUCCESS in 2m 39s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1308/ : SUCCESS in 2m 58s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/69/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1040/ : SUCCESS in 1m 04s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1309/ : SUCCESS in 1m 24s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1421/ : FAILURE in 33m 49s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul-el7/6/ : SUCCESS in 35m 19s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/202/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1041/ : SUCCESS in 3m 02s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1310/ : SUCCESS in 1m 27s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/70/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1042/ : SUCCESS in 1m 13s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1311/ : SUCCESS in 3m 08s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1422/ : FAILURE in 30m 44s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul-el7/7/ : SUCCESS in 43m 10s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/71/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1043/ : SUCCESS in 1m 48s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1312/ : SUCCESS in 1m 19s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1423/ : FAILURE in 32m 05s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul-el7/8/ : SUCCESS in 34m 55s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/203/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1046/ : SUCCESS in 1m 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1315/ : SUCCESS in 1m 25s

**Comment by panjan** [comment]
tests passed: https://travis-ci.org/kubamahnert/gooddata-ruby/builds/388297675

**Pull request merged**
