### PR TITLE
TMA-601: Remove CLIENT_ID setting from LCM bricks

### PR DESCRIPTION
**Pull request by jimirocks**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/873/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/735/ : SUCCESS in 36s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1002/ : SUCCESS in 2m 00s

**Comment by jimirocks** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/874/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1276/ : FAILURE in 8m 55s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1040/ : UNSTABLE in 24m 27s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/878/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1277/ : FAILURE in 51m 38s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1041/ : UNSTABLE in 43m 57s

**Comment by jimirocks** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/905/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1293/ : FAILURE in 50m 34s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1057/ : UNSTABLE in 29m 14s

**Comment by jimirocks** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/906/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1294/ : SUCCESS in 59m 41s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1058/ : UNSTABLE in 32m 22s

**Comment by jimirocks** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/907/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1295/ : SUCCESS in 57m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1059/ : SUCCESS in 31m 08s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/320/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/756/ : SUCCESS in 2m 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1024/ : SUCCESS in 2m 06s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1296/ : SUCCESS in 54m 14s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/1060/ : SUCCESS in 31m 44s

**Pull request merged**
