### PR TITLE
BUGFIX: WA-7699 Stop using deprecated executor3 from gooddata-ruby

### PR DESCRIPTION
**Pull request by bredy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/218/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1084/ : FAILURE in 5s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/244/ : FAILURE in 5s

**Comment by panjan** [comment]
ok to merge

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/238/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1114/ : SUCCESS in 39s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/263/ : SUCCESS in 23s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/239/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/921/ : FAILURE in 45m 45s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/691/ : SUCCESS in 22m 47s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/240/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/922/ : FAILURE in 44m 37s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/692/ : SUCCESS in 21m 24s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/249/ : SUCCESS in 23s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1122/ : FAILURE in 4s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/271/ : SUCCESS in 22s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/252/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1125/ : FAILURE in 4s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/274/ : SUCCESS in 25s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/253/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/924/ : SUCCESS in 45m 33s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/694/ : SUCCESS in 22m 43s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/259/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1131/ : FAILURE in 4s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/280/ : SUCCESS in 24s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/260/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/925/ : SUCCESS in 45m 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/695/ : SUCCESS in 21m 29s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/267/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1137/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/286/ : SUCCESS in 21s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/86/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1138/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/287/ : SUCCESS in 22s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/926/ : SUCCESS in 45m 13s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/696/ : SUCCESS in 21m 11s

**Pull request merged**
