### PR TITLE
TMA-1393 Set limits for LCM namespace

### PR DESCRIPTION
**Pull request by sl4dy**

### CODE REVIEW

**Comment by jimirocks** [comment]
@sl4dy @panjan I believe this should go to master

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1273/ : SUCCESS in 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/63/ : FAILURE in 2h 01m 50s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/10/ : FAILURE in 45s

**Comment by michalvanco** [comment]
+1, lcm check/deploy pipelines for chart are running only on master... see https://github.com/gooddata/ci-infra/blob/master/zuul/layout.yaml#L2222

**Comment by michalvanco** [comment]
@panjan ^

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1284/ : SUCCESS in 24s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/67/ : FAILURE in 20s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/12/ : FAILURE in 29s

**Comment by sl4dy** [comment]
We need to have per-namespace limits elsewhere, they cannot live with helm chart as multiple helm charts can be deployed into a single namespace.

**Pull request closed without merging**
