### PR TITLE
BUGFIX: TMA-1506 fixing unit tests 2.4 failed on xcode9.3

### PR DESCRIPTION
**Pull request by vu-pham**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1596/ : SUCCESS in 17s

**Comment by vu-pham** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1597/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/346/ : SUCCESS in 33s

**Pull request merged**
