### PR TITLE
fixed lcm.rake file

### PR DESCRIPTION
**Pull request by Hahihula**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/320/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1165/ : SUCCESS in 1m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1435/ : SUCCESS in 2m 26s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/322/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1166/ : SUCCESS in 1m 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1436/ : SUCCESS in 2m 21s

**Comment by gdgate** [comment]
Build in pipeline check-extended aborted.

**Pull request merged**
