### PR TITLE
TMA-1234 Release of 2.1.2

### PR DESCRIPTION
**Pull request by Hahihula**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/299/ : FAILURE in 21s
- gooddata-ruby-travis-check : SKIPPED (non-voting)
- gooddata-ruby-lcm-promote-pipeline : SKIPPED

**Comment by kubamahnert** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/300/ : SUCCESS in 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/36/ : FAILURE in 5s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/105/ : FAILURE in 33s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/301/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/37/ : FAILURE in 4s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/106/ : FAILURE in 38s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/302/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/38/ : FAILURE in 5s (non-voting)
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/107/ : SUCCESS in 13m 39s

**Pull request merged**
