### PR TITLE
Remove looping over ObjectSpace

### PR DESCRIPTION
**Pull request by panjan**
RELATED: #995

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/116/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/971/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/117/ : SUCCESS in 23s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/117/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/865/ : SUCCESS in 45m 05s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/639/ : SUCCESS in 22m 44s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/51/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/974/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/120/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/867/ : SUCCESS in 44m 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/641/ : UNSTABLE in 1m 40s

**Comment by vhtien** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/58/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/986/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/132/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/876/ : SUCCESS in 46m 58s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/650/ : SUCCESS in 20m 56s

**Pull request merged**
