### PR TITLE
TMA-583: Regression issue in schedule execution brick

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/168/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1033/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/176/ : SUCCESS in 21s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/79/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1042/ : FAILURE in 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/189/ : FAILURE in 4s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/80/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1043/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/190/ : SUCCESS in 23s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/905/ : FAILURE in 43m 25s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/678/ : UNSTABLE in 5m 14s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/81/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1044/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/191/ : SUCCESS in 21s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/906/ : FAILURE in 43m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/679/ : UNSTABLE in 5m 17s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/83/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1051/ : FAILURE in 4s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/198/ : FAILURE in 6s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/84/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1076/ : SUCCESS in 45s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/230/ : SUCCESS in 24s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/916/ : SUCCESS in 45m 37s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/686/ : SUCCESS in 22m 43s

**Pull request merged**
