### PR TITLE
Support integer type id in Domain#clients

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-450

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/636/ : SUCCESS in 23s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/587/ : FAILURE in 9m 01s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/356/ : UNSTABLE in 9m 45s

**Comment by panjan** [comment]
ok to test - testing

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/680/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/634/ : FAILURE in 45m 02s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/404/ : SUCCESS in 22m 29s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/688/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/642/ : FAILURE in 44m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/413/ : SUCCESS in 26m 06s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/696/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/650/ : FAILURE in 3m 14s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/421/ : FAILURE in 36s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/703/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/657/ : SUCCESS in 54m 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/428/ : UNSTABLE in 22m 22s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/704/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/658/ : FAILURE in 53m 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/429/ : SUCCESS in 24m 18s

**Pull request merged**
