### PR TITLE
TMA-570: Add GOODOT_CUSTOM_PROJECT_ID to metadata

### PR DESCRIPTION
**Pull request by panjan**
FIXES: TMA-570

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/131/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/993/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/139/ : SUCCESS in 20s

**Comment by korczis** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/143/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1004/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/150/ : SUCCESS in 22s

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/150/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 2s
- gooddata-ruby-rubocop-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/69/ : CODE REVIEW VIOLATED in 3s
- gooddata-ruby-rubocop-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/71/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/1011/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/157/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/897/ : SUCCESS in 45m 47s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/670/ : SUCCESS in 21m 05s

**Pull request merged**
