### PR TITLE
FIX: Revert "Use proper server"

### PR DESCRIPTION
**Pull request by korczis**
This reverts commit 906779083f67b580eb5657ff0ede7df1f0853bb4.

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/26/

**Comment by cvengros** [comment]
ok to merge

**Pull request merged**
