### PR TITLE
Remove dependency on nokogiri

### PR DESCRIPTION
**Pull request by panjan**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/553/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/492/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/233/ : FAILURE in 1m 44s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/577/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/517/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/291/ : UNSTABLE in 15m 57s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/597/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/538/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/311/ : SUCCESS in 21m 06s

**Pull request closed without merging**
