### PR TITLE
Fix tests when runing 'rake test:unit'

### PR DESCRIPTION
**Pull request by vhtien**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/828/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/784/ : SUCCESS in 44m 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/556/ : FAILURE in 29s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/32/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/859/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/6/ : SUCCESS in 2m 44s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/35/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/808/ : SUCCESS in 41m 41s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/581/ : UNSTABLE in 15m 20s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/12/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/868/ : FAILURE in 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/15/ : SUCCESS in 3m 18s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/817/ : SUCCESS in 42m 32s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/590/ : SUCCESS in 21m 25s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/14/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/872/ : SUCCESS in 41s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/19/ : SUCCESS in 3m 00s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/820/ : FAILURE in 1h 12m 19s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/593/ : SUCCESS in 22m 06s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/17/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/876/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/23/ : SUCCESS in 3m 06s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/822/ : SUCCESS in 43m 34s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/595/ : FAILURE in 2m 24s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/23/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/882/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/29/ : SUCCESS in 2m 48s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/826/ : SUCCESS in 43m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/599/ : SUCCESS in 23m 02s

**Pull request merged**
