### PR TITLE
BUGFIX: TMA-399 Provisioning brick actions optimization

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/534/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/473/ : FAILURE in 44m 00s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/212/ : FAILURE in 1m 35s

**Comment by vhtien** [comment]
ok to test

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/536/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/475/ : FAILURE in 43m 00s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/214/ : SUCCESS in 1m 33s

**Pull request merged**
