### PR TITLE
FEATURE: TMA-314 New Generic Brick

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/349/ : FAILURE in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/284/ : SUCCESS in 42m 46s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/15/ : FAILURE in 2m 58s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/350/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/285/ : SUCCESS in 42m 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/16/ : FAILURE in 2m 42s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/379/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/314/ : FAILURE in 2m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/45/ : FAILURE in 7m 49s

**Comment by korczis** [comment]
@vhtien There are still some errors - https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/314/console

**Comment by vhtien** [comment]
not yet. I'm waiting for you guys to setup LCM integration tests

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/389/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/324/ : SUCCESS in 41m 37s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/55/ : FAILURE in 8m 06s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/416/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/354/ : FAILURE in 47m 38s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/85/ : SUCCESS in 13m 01s

**Pull request merged**
