### PR TITLE
TMA-809: Fix new visualization object in bricks

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/739/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/601/ : SUCCESS in 1m 57s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/862/ : SUCCESS in 1m 57s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/282/ : FAILURE in 12s
- gooddata-ruby-pronto-code-review-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/283/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/603/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/864/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1207/ : SUCCESS in 54m 14s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/966/ : SUCCESS in 31m 35s

**Pull request merged**
