### PR TITLE
TMA-620: Fix token for Staging1

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/359/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/98/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/408/ : SUCCESS in 31s

**Comment by panjan** [comment]
extended test

**Comment by hacxman** [comment]
seems that token created this way works for me

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/360/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1007/ : FAILURE in 1h 21m 53s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/765/ : SUCCESS in 21m 15s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/361/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1008/ : FAILURE in 19m 45s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/766/ : UNSTABLE in 1m 26s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/362/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1009/ : ABORTED in 2h 00m 01s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/767/ : UNSTABLE in 12m 16s

**Comment by panjan** [comment]
extended test - staging

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/363/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1010/ : ABORTED in 3m 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/768/ : ABORTED in 3m 25s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/365/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1011/ : FAILURE in 42m 40s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/769/ : SUCCESS in 23m 20s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/366/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1012/ : FAILURE in 42m 05s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/770/ : SUCCESS in 22m 08s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/368/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1015/ : FAILURE in 44m 08s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/773/ : SUCCESS in 22m 02s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/369/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/104/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/414/ : SUCCESS in 29s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/370/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1016/ : SUCCESS in 42m 21s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/774/ : SUCCESS in 20m 27s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/147/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/105/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/415/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1017/ : SUCCESS in 42m 21s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/775/ : SUCCESS in 21m 50s

**Pull request merged**
