### PR TITLE
TMA-666: Generate junit-formatted test results

### PR DESCRIPTION
**Pull request by panjan**
relates to https://github.com/gooddata/ci-infra/pull/3456

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/510/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/245/ : SUCCESS in 1m 58s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/551/ : SUCCESS in 2m 05s

**Comment by kubamahnert** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/168/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/246/ : SUCCESS in 1m 55s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/552/ : FAILURE in 54s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/169/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/247/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/553/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1064/ : ABORTED in 2h 00m 01s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/823/ : FAILURE in 42s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/170/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/250/ : SUCCESS in 33s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/556/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1065/ : ABORTED in 2h 00m 00s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/824/ : SUCCESS in 23m 26s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/171/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/255/ : SUCCESS in 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/561/ : SUCCESS in 2m 21s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1066/ : ABORTED in 2h 00m 02s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/825/ : UNSTABLE in 16m 42s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/173/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/259/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/566/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1067/ : ABORTED in 3m 35s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/826/ : FAILURE in 59s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/179/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/268/ : SUCCESS in 1m 46s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/575/ : SUCCESS in 1m 47s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1074/ : FAILURE in 45m 28s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/833/ : UNSTABLE in 3m 45s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/523/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1075/ : SUCCESS in 43m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/834/ : UNSTABLE in 1m 39s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/183/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/273/ : SUCCESS in 38s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/580/ : SUCCESS in 39s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1079/ : SUCCESS in 43m 27s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/838/ : UNSTABLE in 17m 27s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/184/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/274/ : SUCCESS in 1m 46s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/581/ : SUCCESS in 1m 46s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1080/ : SUCCESS in 44m 52s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/839/ : SUCCESS in 21m 49s

**Pull request merged**
