### PR TITLE
Synchronize only additional hidden params

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-340

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/719/ : FAILURE in 19s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/673/ : FAILURE in 3m 20s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/444/ : FAILURE in 35s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/720/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/674/ : FAILURE in 3m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/445/ : UNSTABLE in 20m 50s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/723/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/677/ : FAILURE in 45m 09s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/448/ : FAILURE in 24s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/730/ : SUCCESS in 30s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/684/ : FAILURE in 45m 32s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/455/ : UNSTABLE in 20m 51s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/732/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/686/ : FAILURE in 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/457/ : UNSTABLE in 20m 22s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/733/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/687/ : SUCCESS in 42m 50s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/458/ : UNSTABLE in 20m 27s

**Pull request merged**
