### PR TITLE
Fix syncing hidden params in SynchronizeSchedules

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-340

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/748/ : FAILURE in 34s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/703/ : FAILURE in 43m 59s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/473/ : UNSTABLE in 5m 58s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/749/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/704/ : FAILURE in 40m 14s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/474/ : UNSTABLE in 5m 52s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/753/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/708/ : ABORTED in 2m 31s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/478/ : FAILURE in 31s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/754/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/709/ : SUCCESS in 43m 31s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/479/ : UNSTABLE in 20m 40s

**Pull request merged**
