### PR TITLE
FEATURE: TMA-1165 Remove unused info bricks

### PR DESCRIPTION
**Pull request by sadam21**
* PrintActions
* PrintModes
* PrintTypes

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/794/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1610/ : SUCCESS in 3m 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1871/ : SUCCESS in 2m 51s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/52/ : SUCCESS in 7m 44s

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/796/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1612/ : SUCCESS in 2m 49s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1873/ : FAILURE in 2m 46s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/54/ : SUCCESS in 7m 48s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/797/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1613/ : SUCCESS in 3m 04s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1874/ : SUCCESS in 1m 11s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/55/ : SUCCESS in 7m 31s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/801/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1617/ : SUCCESS in 1m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1878/ : SUCCESS in 1m 09s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/57/ : SUCCESS in 7m 37s

**Pull request merged**
