### PR TITLE
FEATURE: TMA-208 Add support for Automated Data Distribution (ADD) to…

### PR DESCRIPTION
**Pull request by vhtien**
… Ruby SDK

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/111/ : FAILURE in 17s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/112/ : FAILURE in 6s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/113/ : FAILURE in 5s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/114/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/76/ : FAILURE in 15m 51s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/115/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/77/ : FAILURE in 1m 26s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/117/ : FAILURE in 8s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/118/ : FAILURE in 17s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/122/ : FAILURE in 7s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by korczis** [comment]
@vhtien Can you rebase this PR, pls?

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/124/ : FAILURE in 6s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by korczis** [comment]
LGTM

**Pull request merged**
