### PR TITLE
TMA-608: RubySDK: MandatoryUserFilter methods returns nil

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/323/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/47/ : FAILURE in 2m 46s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/361/ : FAILURE in 40s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/324/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/48/ : FAILURE in 2m 11s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/362/ : FAILURE in 2m 17s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/325/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/49/ : FAILURE in 53s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/363/ : FAILURE in 57s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/332/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/65/ : SUCCESS in 2m 44s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/375/ : SUCCESS in 1m 45s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/336/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/982/ : SUCCESS in 46m 19s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/741/ : UNSTABLE in 25m 48s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/339/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/984/ : SUCCESS in 47m 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/743/ : UNSTABLE in 21m 35s

**Comment by vhtien** [comment]
Fix integration tests: https://ms-gerrit.intgdc.com/#/c/1549/

**Comment by vhtien** [comment]
extended test

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/350/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/989/ : SUCCESS in 50m 59s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/748/ : SUCCESS in 24m 36s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/130/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/78/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/388/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/990/ : SUCCESS in 46m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/749/ : ABORTED in 1h 00m 01s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/134/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/82/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/392/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/994/ : ABORTED in 2h 00m 00s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/753/ : ABORTED in 1h 00m 00s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/135/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/83/ : SUCCESS in 1m 53s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/393/ : SUCCESS in 1m 42s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/995/ : FAILURE in 33m 34s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/754/ : UNSTABLE in 2m 33s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/136/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/84/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/394/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/996/ : FAILURE in 27m 25s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/755/ : UNSTABLE in 2m 10s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/141/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/95/ : SUCCESS in 1m 42s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/405/ : SUCCESS in 1m 44s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1002/ : FAILURE in 28m 32s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/761/ : UNSTABLE in 2m 26s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/145/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/101/ : SUCCESS in 27s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/411/ : SUCCESS in 1m 52s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1013/ : FAILURE in 26m 11s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/771/ : SUCCESS in 21m 50s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/146/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/103/ : SUCCESS in 1m 56s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/413/ : SUCCESS in 1m 49s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1014/ : FAILURE in 2m 01s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/772/ : UNSTABLE in 1m 01s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/372/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/107/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/417/ : SUCCESS in 31s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/148/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/108/ : SUCCESS in 31s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/418/ : SUCCESS in 28s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1018/ : SUCCESS in 42m 15s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/776/ : SUCCESS in 22m 28s

**Pull request merged**
