### PR TITLE
Improve tests for Model

### PR DESCRIPTION
**Pull request by penge**
Make these changes:
* Improve `model_spec.rb`
* Update `rspec` and add `rspec-mocks`
* Fix `Model.title` and `Model.identifier_for`
* Replace `Model.check_gd_datatype` with `Model.has_gd_type?` and `Model.has_gd_datatype?`

Improve test coverage of `GoodData::Model` to **61.9%** (before 36.36%).

### CODE REVIEW

**Comment by korczis** [comment]
Hi Pavel, can you rebase this PR please? It will be pleasure for me merge this :)

**Comment by korczis** [comment]
:+1:

**Comment by penge** [comment]
Sure, wait a minute ;)

**Comment by penge** [comment]
Rebase done.

**Comment by fluke777** [comment]
@penge this is great but this would unfortunately clash with https://github.com/gooddata/gooddata-ruby/pull/498. I will try to merge it once we are in develop.

**Pull request closed without merging**
