### PR TITLE
BUGFIX: MSF-25459 Fixing checking condition not working properly when running parallel synchronize user filters for many workspaces

### PR DESCRIPTION
**Pull request by hung-nguyen-hoang**

### CODE REVIEW

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1560/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1407/ : SUCCESS in 11m 38s

**Comment by gdgate** [comment]
Build in pipeline check-extended aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1562/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1408/ : SUCCESS in 9m 27s

**Comment by danh-ung** [comment]
LGTM

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/43/ : SUCCESS in 15m 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1563/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/38/ : SUCCESS in 18m 08s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/41/ : FAILURE in 12m 00s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/38/ : FAILURE in 1h 10m 40s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/43/ : SUCCESS in 22m 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/41/ : SUCCESS in 14m 06s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/44/ : SUCCESS in 17m 31s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1564/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/39/ : SUCCESS in 16m 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/42/ : FAILURE in 11m 24s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/39/ : FAILURE in 1h 02m 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/44/ : SUCCESS in 21m 27s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/42/ : SUCCESS in 12m 27s

**Comment by hung-nguyen-hoang** [comment]
The failed integration tests don't relate to fixing code.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1942

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/190/ : SUCCESS in 16m 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/142/ : SUCCESS in 2m 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/34/ : FAILURE in 14s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/684/ : SUCCESS in 16s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/106/ : SUCCESS in 1m 00s

**Pull request merged**
