### PR TITLE
FEATURE: TMA-144 Using a new efficient synchronization of process sch…

### PR DESCRIPTION
**Pull request by vhtien**
…edules

### CODE REVIEW

**Comment by vhtien** [comment]
DO NOT MERGE

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/344/ : SUCCESS in 25s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/279/ : SUCCESS in 44m 02s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/10/ : FAILURE in 2m 57s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/345/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/280/ : SUCCESS in 42m 50s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/11/ : SUCCESS in 4m 51s (non-voting)

**Comment by vhtien** [comment]
Replaced by #810

**Pull request closed without merging**
