### PR TITLE
BIA-289: Added ability to add grain to blueprint

### PR DESCRIPTION
**Pull request by fluke777**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/371/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/372/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/373/

**Comment by korczis** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/374/

**Comment by korczis** [comment]
ok to merge but #627 should be merged first

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
