### PR TITLE
Verify Extended test from master, Do not merge

### PR DESCRIPTION
**Pull request by tqtu**

### CODE REVIEW

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/24/ : FAILURE in 1m 03s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/21/ : FAILURE in 1m 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/23/ : FAILURE in 1m 52s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/21/ : FAILURE in 2m 00s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/25/ : FAILURE in 2m 57s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/23/ : FAILURE in 1m 53s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1522/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1377/ : SUCCESS in 20m 07s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/26/ : FAILURE in 2m 03s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/22/ : FAILURE in 2m 14s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/24/ : FAILURE in 1m 32s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/22/ : FAILURE in 2m 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/26/ : FAILURE in 1m 31s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/24/ : FAILURE in 3m 08s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/28/ : FAILURE in 1m 16s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/23/ : FAILURE in 1m 12s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/25/ : FAILURE in 2m 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/23/ : FAILURE in 2m 06s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/27/ : FAILURE in 1m 15s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/25/ : FAILURE in 2m 20s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1528/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1382/ : SUCCESS in 18m 51s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/29/ : FAILURE in 1m 58s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/24/ : FAILURE in 1m 35s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/26/ : FAILURE in 46s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/24/ : FAILURE in 3m 44s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/28/ : FAILURE in 2m 26s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/26/ : FAILURE in 2m 27s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/30/ : FAILURE in 1m 32s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/25/ : FAILURE in 1m 44s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/27/ : FAILURE in 1m 31s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/25/ : FAILURE in 2m 12s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/29/ : FAILURE in 2m 04s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/27/ : FAILURE in 2m 05s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/31/ : FAILURE in 1m 39s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/26/ : FAILURE in 2m 51s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/28/ : FAILURE in 1m 08s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/26/ : FAILURE in 3m 10s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/30/ : FAILURE in 1m 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/28/ : FAILURE in 1m 22s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1531/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1385/ : SUCCESS in 17m 53s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/32/ : FAILURE in 30s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/27/ : FAILURE in 1m 22s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/30/ : FAILURE in 1m 14s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/27/ : FAILURE in 2m 06s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/31/ : FAILURE in 1m 14s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/29/ : FAILURE in 1m 13s

**Comment by tqtu** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/33/ : SUCCESS in 15m 02s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/28/ : SUCCESS in 17m 54s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/31/ : SUCCESS in 12m 55s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/28/ : FAILURE in 1h 11m 25s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/32/ : SUCCESS in 21m 31s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/30/ : FAILURE in 10m 23s

**Pull request closed without merging**
