### PR TITLE
Log error when upload fails

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-557

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/79/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/923/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/69/ : SUCCESS in 34s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/80/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/845/ : SUCCESS in 44m 44s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/618/ : SUCCESS in 20m 05s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/86/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/930/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/76/ : SUCCESS in 21s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/87/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/931/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/77/ : SUCCESS in 17s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/37/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/932/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/78/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/847/ : SUCCESS in 45m 26s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/620/ : SUCCESS in 20m 55s

**Pull request merged**
