### PR TITLE
Update image gdc-java-8-jre to 0dec94a (from gdc-docker-images)

### PR DESCRIPTION
**Pull request by yenkins-admin**
Change HEAD: https://github.com/gooddata/gdc-docker-images/commit/0dec94a
Pipeline run: [gdc-docker-images/gdc-docker-images-tools-build-pipeline](https://jenkins-ii.intgdc.com/job/gdc-docker-images/job/gdc-docker-images-tools-build-pipeline/52/display/redirect)

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/130/ : SUCCESS in 8s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/324/ : FAILURE in 32m 23s

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/131/ : SUCCESS in 9s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/325/ : FAILURE in 12m 32s

**Comment by phong-nguyen-duy** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/135/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/326/ : SUCCESS in 20m 50s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/406/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/82/ : SUCCESS in 47s

**Pull request merged**
