### PR TITLE
Fix standalone calls to rspec expect

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/807/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1621/ : SUCCESS in 1m 20s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1882/ : SUCCESS in 2m 41s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/61/ : SUCCESS in 8m 32s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/808/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1622/ : SUCCESS in 2m 37s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1883/ : SUCCESS in 2m 57s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/62/ : SUCCESS in 7m 59s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/809/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1623/ : SUCCESS in 1m 26s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1884/ : SUCCESS in 1m 13s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/63/ : SUCCESS in 7m 15s

**Comment by panjan** [comment]
https://travis-ci.org/panjan/gooddata-ruby/builds/454970919

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/812/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1626/ : SUCCESS in 1m 05s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1887/ : SUCCESS in 1m 06s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/66/ : SUCCESS in 7m 52s

**Comment by panjan** [comment]
https://travis-ci.org/panjan/gooddata-ruby/jobs/455025571

**Pull request merged**
