### PR TITLE
Enable VCR under ruby >= 2.4

### PR DESCRIPTION
**Pull request by jimirocks**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/186/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1022/ : SUCCESS in 2m 23s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1291/ : SUCCESS in 2m 24s

**Comment by jimirocks** [comment]
do not merge yet, needs more investigation since its break recordings

**Comment by jimirocks** [comment]
build success: https://travis-ci.org/jimirocks/gooddata-ruby/builds/386606290

**Comment by kubamahnert** [comment]
merged due to https://travis-ci.org/jimirocks/gooddata-ruby/builds/386606290

**Comment by kubamahnert** [comment]
LGTM!

**Pull request merged**
