### PR TITLE
Add Test.md

### PR DESCRIPTION
**Pull request by korczis**
🛑  DO NOT MERGE 🛑 

This PR is just to test https://jira.intgdc.com/browse/TMA-526

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/827/ : SUCCESS in 43s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/783/ : SUCCESS in 44m 36s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/555/ : FAILURE in 31s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/834/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/790/ : FAILURE in 2m 59s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/562/ : UNSTABLE in 13m 45s

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/2/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/837/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/793/ : FAILURE in 3m 14s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/565/ : UNSTABLE in 12m 53s

**Comment by jimirocks** [comment]
Closing as TMA-526 is completed some time...

**Pull request closed without merging**
