### PR TITLE
Fix editorconfig

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/867/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1680/ : SUCCESS in 3m 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1941/ : SUCCESS in 3m 00s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/118/ : SUCCESS in 7m 41s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/868/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1681/ : SUCCESS in 1m 14s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1942/ : SUCCESS in 1m 09s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/119/ : SUCCESS in 8m 38s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/141/ : SUCCESS in 11s

**Pull request merged**
