### PR TITLE
[BIA-20] - Use proper server

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by korczis** [comment]
Related to BIA-28

**Comment by korczis** [comment]
@cvengros Petr, can you please review this?

**Comment by cvengros** [comment]
ok to merge

**Comment by korczis** [comment]
Fuck, this must be merged to develop. Let me fix this.

**Comment by korczis** [comment]
Proper PR - https://github.com/gooddata/gooddata-ruby/pull/432

@cvengros Can you take a look, please?

**Pull request closed without merging**
