### PR TITLE
BUGFIX: TMA-316 Enable adding user logins similar to whitelisted to p…

### PR DESCRIPTION
**Pull request by vhtien**
…rojects

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/327/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/263/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/55/ : FAILURE in 2m 53s (non-voting)

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/328/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/264/ : FAILURE in 44m 31s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/56/ : FAILURE in 2m 51s (non-voting)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/329/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/265/ : FAILURE in 43m 57s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/57/ : FAILURE in 2m 34s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/330/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/266/ : SUCCESS in 43m 11s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/59/ : FAILURE in 3m 16s (non-voting)

**Comment by korczis** [comment]
LGTM

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/332/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/268/ : SUCCESS in 43m 33s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/62/ : SUCCESS in 4m 56s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/334/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/270/ : SUCCESS in 42m 26s
- https://ci.intgdc.com/job/gooddata-lcm-zuul/65/ : FAILURE in 4m 41s (non-voting)

**Pull request merged**
