### PR TITLE
Merge master to develop

### PR DESCRIPTION
**Pull request by vu-pham**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1605/ : SUCCESS in 9s

**Comment by vu-pham** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1606/ : SUCCESS in 12s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/348/ : SUCCESS in 28s

**Pull request merged**
