### PR TITLE
Remove pry

### PR DESCRIPTION
**Pull request by racerpeter**
Since pry is a development tool, it is inadvisable to require it as a production dependency.

Although the jack_in functionality is useful, you can achieve the same thing with existing tools (Rails console for example).

Finally, I would propose that it is better to defer the decision of requiring Pry or not to the project that uses the gem.

Thoughts? And thanks again Tomas for your help this week.

cc @AnnaMhairi @diclophis

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/38/ : FAILURE in 22s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by diclophis** [comment]
This is highly desirable to get merged as soon as possible

**Comment by fluke777** [comment]
@diclophis 

We definitely want to incorporate this asap but we cannot remove it outright since a lot of people use this functionality. I definitely can see there are couple of spurious requires of pry. That is my mistake and I will remove them asap. As for the pry dependency itself we want to isolate pry to only that one particular command first. Second we want to somehow remove it. I see couple of options and would welcome your input on this.

- split the library into two gems gooddata/core and gooddata. Core would be just the library, gooddata would be as it is for backward compatibility.
- not sure if gems provide any flexibility to somehow give the user the flexibility to omit some dependencies
- We are not hung up on pry. We can use any REPL. Is there specific reason why you want to avoid pry? Is there an alternative that would be acceptable? When I looked at it initially it seemed like the library everybody recommended so I just grabbed it.

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by korczis** [comment]
@racerpeter there is no pry dependency now. Btw, 0.6.50 is going to be released soon. Stay tuned.

Sorry for late reply.

**Pull request closed without merging**
