### PR TITLE
II-448: Move configuration from Jenkinsfile

### PR DESCRIPTION
**Pull request by michalvanco**
`Pipeline.get(...)` is getting deprecated.

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/20/ : SUCCESS in 1m 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1574/ : SUCCESS in 11s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/212/ : FAILURE in 10m 00s

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/21/ : SUCCESS in 1m 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1575/ : SUCCESS in 11s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/213/ : FAILURE in 10m 45s

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/22/ : FAILURE in 10m 00s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1582/ : SUCCESS in 11s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/215/ : FAILURE in 18m 44s

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/23/ : SUCCESS in 1m 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1587/ : SUCCESS in 14s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/216/ : SUCCESS in 20m 28s

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/340/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/47/ : SUCCESS in 25s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-deploy-pipeline/12/ : SUCCESS in 1m 16s

**Pull request merged**
