### PR TITLE
Fix tests again

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/23/ : FAILURE in 39m 19s

**Comment by hrubi** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/24/ : FAILURE in 40m 54s

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/25/ : FAILURE in 24m 28s

**Pull request closed without merging**
