### PR TITLE
Fixing the tests

### PR DESCRIPTION
**Pull request by fluke777**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/7/ : ABORTED in 2h 00m 00s

**Comment by fluke777** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/8/ : FAILURE in 1h 07m 41s

**Comment by fluke777** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/9/ : FAILURE in 1h 08m 36s

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/10/ : FAILURE in 18s

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/11/ : FAILURE in 14s

**Comment by korczis** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/12/ : FAILURE in 15s

**Comment by fluke777** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/14/ : FAILURE in 14s

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/15/ : SUCCESS in 1h 15m 36s

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
