### PR TITLE
TMA-474 Provide current login user in 403 Forbidden: Can be accessed …

### PR DESCRIPTION
**Pull request by vhtien**
…only by domain admin error message

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/699/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/653/ : FAILURE in 5m 07s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/424/ : FAILURE in 38s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/739/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/693/ : FAILURE in 3m 13s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/464/ : FAILURE in 28s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/761/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/716/ : FAILURE in 3m 24s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/486/ : SUCCESS in 21m 40s

**Comment by panjan** [comment]
This seems to be a legit failure: https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/716/

@vhtien

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/768/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/724/ : SUCCESS in 44m 40s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/494/ : SUCCESS in 19m 23s

**Pull request merged**
