### PR TITLE
TMA-526: Some AppStore LCM Tests tests fail

### PR DESCRIPTION
**Pull request by korczis**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/14/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/848/ : FAILURE in 14s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/15/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/799/ : FAILURE in 18s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/571/ : UNSTABLE in 10m 42s

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/16/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/800/ : FAILURE in 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/572/ : UNSTABLE in 12m 46s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/18/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/850/ : FAILURE in 15s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/20/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/852/ : SUCCESS in 14s

**Comment by korczis** [comment]
extended test

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/21/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/801/ : FAILURE in 2m 54s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/573/ : UNSTABLE in 15m 15s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/22/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/853/ : SUCCESS in 16s

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/23/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/802/ : SUCCESS in 44m 22s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/574/ : UNSTABLE in 14m 26s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/24/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/854/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1/ : SUCCESS in 2m 42s

**Comment by korczis** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/25/ : SUCCESS in 4s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/803/ : SUCCESS in 42m 09s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/575/ : UNSTABLE in 4m 12s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/26/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/804/ : SUCCESS in 41m 39s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/576/ : UNSTABLE in 13m 46s

**Comment by panjan** [comment]
Closing as this was solved in https://ms-gerrit.intgdc.com/#/c/608/

**Pull request closed without merging**
