### PR TITLE
Add logging input data to #collect_clients

### PR DESCRIPTION
**Pull request by panjan**
## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/639/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/590/ : FAILURE in 12m 55s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/359/ : UNSTABLE in 15m 06s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/648/ : FAILURE in 4s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/599/ : FAILURE in 44m 57s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/368/ : SUCCESS in 22m 00s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/684/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/638/ : SUCCESS in 45m 19s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/408/ : SUCCESS in 23m 18s

**Pull request merged**
