### PR TITLE
Make activesupport a runtime dependency

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/759/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/620/ : SUCCESS in 1m 58s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/881/ : SUCCESS in 1m 59s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/286/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/621/ : SUCCESS in 1m 51s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/882/ : SUCCESS in 2m 00s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1214/ : FAILURE in 20s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/973/ : FAILURE in 1m 11s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/287/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/622/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/883/ : SUCCESS in 32s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1215/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/974/ : FAILURE in 57s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/288/ : SUCCESS in 35s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/623/ : SUCCESS in 1m 52s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/884/ : SUCCESS in 36s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1217/ : SUCCESS in 52m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/975/ : FAILURE in 1m 11s

**Comment by kubamahnert** [comment]
The failure was expected as the fix is to be merged into appstore.

**Pull request merged**
