### PR TITLE
Added a dry run to adding users

### PR DESCRIPTION
**Pull request by fluke777**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/17/ : FAILURE in 37m 56s

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/18/ : FAILURE in 37m 10s

**Comment by fluke777** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/19/ : FAILURE in 38m 55s

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/20/ : SUCCESS in 1h 17m 05s

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
