### PR TITLE
BIA-162: Added unlisted. Changed deprecated to return true/false. Setter still…

### PR DESCRIPTION
**Pull request by fluke777**
… accepts the old values

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/183/

**Comment by korczis** [comment]
ok to merge

**Pull request merged**
