### PR TITLE
TMA-801: Update rubocop

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/616/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1438/ : FAILURE in 55s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1706/ : SUCCESS in 1m 20s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/617/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1439/ : FAILURE in 1m 06s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1707/ : SUCCESS in 1m 15s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/618/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1441/ : FAILURE in 1m 40s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1708/ : FAILURE in 3m 43s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/623/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1451/ : FAILURE in 57s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1713/ : FAILURE in 1m 00s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/653/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1481/ : FAILURE in 2m 56s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1742/ : FAILURE in 2m 11s

**Comment by kubamahnert** [comment]
LGTM!

**Pull request merged**
