### PR TITLE
SETI-1595: rotating passwords

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/760/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/624/ : SUCCESS in 2m 05s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/885/ : SUCCESS in 2m 06s

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/762/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1218/ : FAILURE in 2m 32s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/976/ : SUCCESS in 39m 49s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/770/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1225/ : SUCCESS in 52m 03s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/983/ : SUCCESS in 40m 27s

**Pull request merged**
