### PR TITLE
New appstore link

### PR DESCRIPTION
**Pull request by fluke777**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/482/

**Comment by fluke777** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/483/

**Comment by korczis** [comment]
Appstore is hosted on internal gerrit now.

**Pull request closed without merging**
