### PR TITLE
TMA-551 Should wait for process is created in case async task

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/75/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/915/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/61/ : SUCCESS in 16s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/32/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/918/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/64/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/841/ : FAILURE in 44m 40s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/614/ : SUCCESS in 22m 46s

**Comment by panjan** [comment]
It looks like the build failure is legit. @vhtien

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/35/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/921/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/67/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/844/ : SUCCESS in 44m 54s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/617/ : SUCCESS in 20m 14s

**Pull request merged**
