### PR TITLE
TMA-574: Fix loading ArrayType class

### PR DESCRIPTION
**Pull request by panjan**
RELATED: TMA-574

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/107/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/962/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/108/ : FAILURE in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/109/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/964/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/110/ : SUCCESS in 15s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/110/ : SUCCESS in 5s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/863/ : SUCCESS in 45m 27s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/637/ : SUCCESS in 22m 43s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/50/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/969/ : SUCCESS in 1m 07s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/115/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/864/ : SUCCESS in 45m 17s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/638/ : SUCCESS in 19m 49s

**Pull request merged**
