### PR TITLE
Aws 2.0

### PR DESCRIPTION
**Pull request by gtaschuk**

### CODE REVIEW

**Comment by yenkins-admin** [comment]
Merged build triggered.

**Comment by yenkins-admin** [comment]
Merged build started.

**Comment by yenkins-admin** [comment]
Merged build finished.

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/BIA-pull-request-builder/118/

**Comment by fluke777** [comment]
@gtaschuk 

Thanks Greg this is very helpful. We have to run it through some internal testing but I will try to push this through asap.

**Comment by korczis** [comment]
Will be addressed soon, part of upcoming release ...

**Pull request closed without merging**
