### PR TITLE
DC-1701: Bump SDK version to 2.1.16

### PR DESCRIPTION
**Pull request by sangtm**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/631/ : SUCCESS in 6s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/612/ : FAILURE in 4m 53s

**Comment by danh-ung** [comment]
LGTM

**Review by danh-ung — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-el7/35/ : FAILURE in 27s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/518/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-travis-check/160/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/74/ : FAILURE in 3m 06s (non-voting)

**Pull request merged**
