### PR TITLE
TMA-1071: Reenable VCR

### PR DESCRIPTION
**Pull request by panjan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/655/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1483/ : FAILURE in 1m 31s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1744/ : FAILURE in 1m 03s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/656/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1484/ : FAILURE in 1m 02s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1745/ : SUCCESS in 2m 36s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/657/ : SUCCESS in 36s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1485/ : FAILURE in 1m 10s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1746/ : SUCCESS in 1m 10s

**Comment by panjan** [comment]
Build passed: https://travis-ci.org/panjan/gooddata-ruby/builds/436645401

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/660/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1488/ : FAILURE in 1m 04s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1749/ : FAILURE in 1m 17s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/662/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1490/ : FAILURE in 1m 00s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1751/ : SUCCESS in 1m 07s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/664/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1492/ : SUCCESS in 1m 08s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1753/ : FAILURE in 1m 06s

**Comment by Hahihula** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/665/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1540/ : FAILURE in 2m 40s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul/101/ : FAILURE in 2m 11s

**Comment by panjan** [comment]
Build passed: https://travis-ci.org/panjan/gooddata-ruby/builds/436645401

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/674/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1501/ : SUCCESS in 1m 10s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1762/ : FAILURE in 1m 23s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/2/ : FAILURE in 14s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/681/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1508/ : FAILURE in 1m 01s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1769/ : FAILURE in 1m 18s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/8/ : SUCCESS in 6m 07s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/684/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1511/ : SUCCESS in 1m 30s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1772/ : FAILURE in 1m 33s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/11/ : SUCCESS in 5m 37s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/686/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1513/ : FAILURE in 1m 29s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1774/ : SUCCESS in 1m 28s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/13/ : SUCCESS in 6m 13s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/696/ : SUCCESS in 15s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1523/ : FAILURE in 1m 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1784/ : SUCCESS in 1m 12s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-check-pipeline/23/ : SUCCESS in 5m 32s

**Pull request closed without merging**
