### PR TITLE
TMA-528: Update rest-client dependency to latest version to make SDK …

### PR DESCRIPTION
**Pull request by vhtien**
…compatible with ruby 2.4

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/290/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 7s
- gooddata-ruby-pronto-code-review-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/291/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 6s
- gooddata-ruby-pronto-code-review-zuul : SKIPPED
- gooddata-ruby-unit-tests-zuul : SKIPPED

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/293/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/9/ : SUCCESS in 2m 10s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/320/ : SUCCESS in 1m 50s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/294/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/944/ : FAILURE in 9s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/713/ : SUCCESS in 23m 54s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/295/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/945/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/714/ : SUCCESS in 22m 54s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/296/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/952/ : FAILURE in 0s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/719/ : SUCCESS in 21m 33s

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/300/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/958/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/721/ : SUCCESS in 21m 55s

**Comment by panjan** [comment]
ok to merge

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/301/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/959/ : FAILURE in 1s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/722/ : SUCCESS in 22m 03s

**Comment by panjan** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/302/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/960/ : FAILURE in 49m 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/723/ : SUCCESS in 23m 13s

**Comment by panjan** [comment]
The build failure seems legit ^^^ @vhtien

**Comment by vhtien** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/313/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/963/ : SUCCESS in 49m 01s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/726/ : SUCCESS in 22m 56s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/110/ : SUCCESS in 50s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/27/ : SUCCESS in 1m 04s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/338/ : FAILURE in 1s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/111/ : SUCCESS in 46s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/28/ : SUCCESS in 1m 49s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/339/ : FAILURE in 0s
- gooddata-ruby-integration-tests-zuul : SKIPPED
- gooddata-ruby-lcm-integration-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/112/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/32/ : SUCCESS in 2m 36s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/343/ : SUCCESS in 2m 22s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/964/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/727/ : UNSTABLE in 2m 32s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/117/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/40/ : SUCCESS in 1m 21s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/354/ : SUCCESS in 44s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/970/ : SUCCESS in 45m 46s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/731/ : SUCCESS in 23m 35s

**Pull request merged**
