### PR TITLE
BUGFIX: TMA-1700 Failed Provisioning Brick created clients without ETL

### PR DESCRIPTION
**Pull request by dangdinh**
Due to hitting daily limit of max created projects so provisioning brick create many client workspace without ETL or empty project.
We should do:
- Delete all invalid clients if exceed limit of max created projects.
- Keep successful client workspace and then do the rest next run to cover ETL sync.

Below is sample exception related to daily limit of max created projects we try on Staging LCM:
`{\"errorCode\"=>\"lcm.provisioning.nested.error\", \"message\"=>\"Nested error '%s'\", \"parameters\"=>[\"{\\\"error\\\":{\\\"parameters\\\":[\\\"3\\\",\\\"4\\\"],\\\"requestId\\\":\\\"c9wxf2TdXV49_4kh3w-AgQ:Bpg7l2npiC9Szhp4vk6_Vw:VhHrUmYhjyMfiEcYqunLjA:AkDTFvVsc11bN6Gj:ToCBfkA4nf49I99b:dtk04wOlXTjsI66Q:zkmom0ii09jxs9hf\\\",\\\"component\\\":\\\"GDC::Quotas::Check\\\",\\\"errorClass\\\":\\\"GDC::Exception::Limit\\\",\\\"message\\\":\\\"Max number registered projects for one group is %s. You have had %s projects. For more information, see https://help.gooddata.com/display/doc/Create+a+Project\\\"}}\"]}",`

`{"errorCode"=>"lcm.provisioning.nested.error", "message"=>"Nested error '%s'", "parameters"=>["{\"error\":{\"component\":\"www-proxy\",\"errorClass\":\"TooManyProjectsCreatedException\",\"errorCode\":\"gdc.error\",\"errorId\":\"9a8a415b-d144-42ca-a644-7c6f899ee958\",\"message\":\"Too many projects created\",\"parameters\":[]}}"]}
`

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/708/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/709/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/710/ : SUCCESS in 12s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/711/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 1m 30s

**Comment by dangdinh** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/712/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/713/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/714/ : SUCCESS in 8s

**Comment by hung-nguyen-hoang** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1763

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/533/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/4/ : SUCCESS in 2m 33s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul-el7/89/ : SUCCESS in 1m 23s (non-voting)

**Pull request merged**
