### PR TITLE
RELATED: TMA-378 Optimize the number of import/export in all LCM bricks

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/488/ : FAILURE in 14s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/427/ : FAILURE in 42m 16s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/164/ : SUCCESS in 1m 24s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/490/ : FAILURE in 10s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/429/ : FAILURE in 42m 33s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/166/ : SUCCESS in 1m 57s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/491/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/430/ : FAILURE in 40m 56s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/167/ : SUCCESS in 1m 48s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/492/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/431/ : SUCCESS in 42m 56s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/168/ : SUCCESS in 1m 48s

**Pull request merged**
