### PR TITLE
BUGFIX: MSF-26016 Update jruby-openssl dependency for LCM Bricks

### PR DESCRIPTION
**Pull request by hung-nguyen-hoang**

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1665/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1488/ : SUCCESS in 9m 22s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/68/ : SUCCESS in 16m 55s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1666/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/62/ : SUCCESS in 19m 09s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/65/ : FAILURE in 12m 25s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/64/ : FAILURE in 1h 13m 11s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/67/ : SUCCESS in 27m 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/66/ : SUCCESS in 16m 17s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1667/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1489/ : SUCCESS in 9m 22s

**Pull request closed without merging**
