### PR TITLE
RELATED: TMA-275 Use rubydev+tester@gooddata.com for tests

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/248/ : FAILURE in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/183/ : FAILURE in 1m 32s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/250/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/185/ : FAILURE in 40m 15s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/251/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/186/ : FAILURE in 1h 11m 18s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/252/ : FAILURE in 8s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/187/ : SUCCESS in 40m 44s

**Comment by vhtien** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/253/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/188/ : SUCCESS in 41m 14s

**Pull request merged**
