### PR TITLE
TMA-775: reading attributes without lazy enumerators:

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/695/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/530/ : FAILURE in 2m 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/807/ : SUCCESS in 2m 07s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/696/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1184/ : FAILURE in 2m 13s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/942/ : ABORTED in 1h 00m 04s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/697/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/531/ : SUCCESS in 44s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/808/ : SUCCESS in 2m 08s

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/702/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1187/ : FAILURE in 3m 37s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/945/ : UNSTABLE in 42m 57s

**Pull request closed without merging**
