### PR TITLE
BUGFIX: MSF-25800 Add SSLErrorWaitReadable error to retry error list

### PR DESCRIPTION
**Pull request by hung-nguyen-hoang**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1586/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1426/ : SUCCESS in 9m 32s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1587/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1427/ : SUCCESS in 9m 09s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1588/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1428/ : SUCCESS in 9m 14s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1589/ : SUCCESS in 3s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1429/ : SUCCESS in 9m 10s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1590/ : SUCCESS in 4s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-build-pipeline/1430/ : SUCCESS in 8m 49s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/50/ : FAILURE in 17s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1591/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/45/ : SUCCESS in 16m 34s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/48/ : FAILURE in 10m 35s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/46/ : FAILURE in 1h 07m 15s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/50/ : FAILURE in 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/48/ : FAILURE in 19s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/51/ : FAILURE in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1592/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/46/ : FAILURE in 46s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/49/ : FAILURE in 29s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/47/ : FAILURE in 1h 08m 11s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/51/ : FAILURE in 35s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/49/ : FAILURE in 18s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/52/ : SUCCESS in 14m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1593/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/47/ : FAILURE in 31s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/50/ : FAILURE in 10m 31s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/48/ : FAILURE in 1h 08m 34s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/52/ : SUCCESS in 22m 00s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/50/ : FAILURE in 17s

**Comment by tqtu** [comment]
extended test

**Comment by ngocmanhha** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/53/ : FAILURE in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1594/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/48/ : FAILURE in 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/51/ : FAILURE in 18s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/49/ : SUCCESS in 1h 09m 57s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/53/ : FAILURE in 19s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/51/ : FAILURE in 19s

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by hung-nguyen-hoang** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/55/ : FAILURE in 32s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1596/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/50/ : FAILURE in 1m 32s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/53/ : FAILURE in 10m 02s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/51/ : FAILURE in 1h 05m 55s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/55/ : SUCCESS in 20m 14s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/54/ : FAILURE in 33s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-userprov-zuul/56/ : FAILURE in 37s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-oss-check/1597/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-slow-zuul/51/ : SUCCESS in 15m 20s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-others-zuul/54/ : FAILURE in 29s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-integration-tests-zuul/52/ : FAILURE in 1h 07m 07s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-release-zuul/56/ : FAILURE in 34s
- https://checklist.intgdc.com/job/lcm/job/gooddata-lcm-ruby-integration-e2e-zuul/55/ : SUCCESS in 11m 53s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ruby-gate-PR1948

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-lcm-promote-pipeline/193/ : SUCCESS in 7m 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-sonarqube-scan-zuul-gate/149/ : SUCCESS in 2m 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-fossa-scanning-zuul/41/ : FAILURE in 2m 08s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/691/ : SUCCESS in 9s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-gitops-deploy-pipeline/113/ : SUCCESS in 53s

**Pull request merged**
