### PR TITLE
TMA-782: do not rely on spec extensions

### PR DESCRIPTION
**Pull request by kubamahnert**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/833/ : SUCCESS in 29s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1647/ : SUCCESS in 1m 13s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1908/ : SUCCESS in 2m 50s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/85/ : SUCCESS in 7m 42s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/836/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-pronto-code-review-zuul/1650/ : SUCCESS in 1m 13s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/1911/ : SUCCESS in 1m 15s
- https://jenkins-ii.intgdc.com/job/gooddata-ruby/job/gooddata-ruby-build-pipeline/88/ : SUCCESS in 7m 44s

**Comment by kubamahnert** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/838/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/1556/ : FAILURE in 11s
- https://checklist.intgdc.com/job/lcm/job/gooddata-ruby-lcm-integration-tests-zuul/115/ : FAILURE in 1m 46s

**Pull request merged**
