### PR TITLE
TMA-576: Missing check in blueprint validation

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-opensource-repository-check/121/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/978/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/124/ : SUCCESS in 20s

**Comment by panjan** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/55/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/980/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/126/ : SUCCESS in 20s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/873/ : FAILURE in 51m 02s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/647/ : SUCCESS in 21m 07s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-merge-compliance-check/57/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/985/ : SUCCESS in 16s
- https://ci.intgdc.com/job/gooddata-ruby-unit-tests-zuul/131/ : SUCCESS in 19s
- https://ci.intgdc.com/job/gooddata-ruby-integration-tests-zuul/875/ : SUCCESS in 45m 04s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/649/ : SUCCESS in 20m 44s

**Pull request merged**
