### PR TITLE
FEATURE: TMA-783 Use SST for ADS connection as default

### PR DESCRIPTION
**Pull request by phong-nguyen-duy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1635/ : SUCCESS in 10s

**Comment by vu-pham** [comment]
@phong-nguyen-duy please update integration tests to cover the changes, such as
 removing ads_client|username, ads_client|password in schedule parameters of any brick in provisioning,release... bricks.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1636/ : SUCCESS in 6s

**Comment by phong-nguyen-duy** [comment]
@vu-pham I updated one test case in user_filters_brick_spec to cover the changes

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1637/ : SUCCESS in 8s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1638/ : SUCCESS in 12s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-opensource-repository-check/1639/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ruby-merge-compliance-check/360/ : SUCCESS in 21s

**Pull request merged**
