### PR TITLE
Remove dependency on aws-sdk-v1

### PR DESCRIPTION
**Pull request by panjan**
This also removes the dependency on nokogiri.

FIXES: TMA-473

## Todos
- [x] Tests
- [ ] Documentation
- [x] Changelog
- [ ] Build passing

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/745/ : SUCCESS in 40s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/699/ : FAILURE in 3m 23s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/470/ : FAILURE in 1m 23s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/746/ : SUCCESS in 17s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/700/ : ABORTED in 12m 05s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/471/ : FAILURE in 25s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/747/ : SUCCESS in 11s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/701/ : FAILURE in 1h 02m 23s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/472/ : FAILURE in 1m 08s

**Comment by panjan** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/757/ : SUCCESS in 34s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/712/ : SUCCESS in 44m 33s
- https://ci.intgdc.com/job/gooddata-ruby-lcm-integration-tests-zuul/482/ : FAILURE in 1m 24s

**Pull request merged**
