### PR TITLE
BUGFIX: BIA-541 Use the simplecov version 0.12.x

### PR DESCRIPTION
**Pull request by vhtien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/71/ : FAILURE in 24s
- gooddata-ruby-tests-zuul : SKIPPED

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-ruby-rubocop-zuul/72/ : SUCCESS in 13s
- https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/54/ : FAILURE in 39m 00s

**Comment by am-gd-cz** [comment]
as far as I can see, there's still 2 tests failing: https://ci.intgdc.com/job/gooddata-ruby-tests-zuul/54/console

**Comment by vhtien** [comment]
@am-gd-cz this ticket just mentions about we cannot run spec to test, not make all tests stable. By the way, the tests are failed because of permission when sync clients, I guess. So I think this PR is ready to merge

**Comment by am-gd-cz** [comment]
ah, yes, you are right

**Comment by am-gd-cz** [comment]
ok to merge

**Pull request merged**
